import QtQuick 2.2

ListModel {
    property string name: "02.7_Handling_Obj._and_Beings"
    ListElement { txt: "abmachen<br>(abmachen, machte ab, hat abgemacht)<br><br>Bitte machen Sie das Preisschild ab!"; tr: "take off<br><br>Please take off the price tag."; known: false }
    ListElement { txt: "ändern<br>(ändern, änderte, hat geändert)<br><br>Das Gesetz wurde geändert. Meine Adresse hat sich geändert."; tr: "change<br><br>The law was changed. My address has changed."; known: false }
    ListElement { txt: "Änderung<br>(die Änderung, die Änderungen)<br><br>Mit der Änderung des Vertrags war sie einverstanden."; tr: "change<br><br>She agreed to the change in the contract."; known: false }
    ListElement { txt: "anwenden<br>(anwenden, wendete an, hat angewendet)<br><br>Weißt du, wie man dieses Mittel anwendet?"; tr: "use<br><br>Do you know how to use this material?"; known: false }
    ListElement { txt: "aufhalten<br>(aufhalten, hielt auf, hat aufgehalten)<br><br>Sie hielt der Kundin die Tür auf."; tr: "hold open<br><br>She held the door open for the customer."; known: false }
    ListElement { txt: "aufhören<br>(aufhören, hörte auf, hat aufgehört.)<br><br>Wann hörst du mit der Arbeit auf?"; tr: "stop (doing something), finish<br><br>When da you finish work?"; known: false }
    ListElement { txt: "aufräumen<br>(aufräumen, räumte auf, hat aufgeräumt)<br><br>Der Keller muss unbedingt aufgeräumt werden."; tr: "straighten up, clean up<br><br>The cellar has to be cleaned up by all means."; known: false }
    ListElement { txt: "benutzen<br>(benutzen, benutzte, hat benutzt)<br><br>Darf ich mal Ihr Telefon benutzen?"; tr: "use<br><br>May I use your telephone?"; known: false }
    ListElement { txt: "bereit (sein)<br>(bereit (sein))<br><br>Bist du bereit mitzumachen?"; tr: "ready<br><br>Are you ready and willing to join in?"; known: false }
    ListElement { txt: "berühren<br>(berühren, berührte, hat berührt)<br><br>Sie dürfen das Bild ansehen, aber nicht berühren."; tr: "touch<br><br>You may look at the picture, but you may not touch it."; known: false }
    ListElement { txt: "biegen<br>(biegen, bog, hat gebogen)<br><br>Wenn du den Ast noch mehr biegst, bricht er ab."; tr: "bend<br><br>If you keep bending the branch, it will break (off)."; known: false }
    ListElement { txt: "brechen<br>(brechen, brach, hat/ist gebrochen)<br><br>Er hat die Schokolade in vier Teile gebrochen. Das Bein ist gebrochen."; tr: "break<br><br>He broke the chocolate bar into four pieces. The leg is broken."; known: false }
    ListElement { txt: "drücken<br>(drücken, drückte, hat gedrückt)<br><br>Die Maschine stoppt, wenn man (auf) diesen Knopf drückt."; tr: "push<br><br>The machine stops when you push this button."; known: false }
    ListElement { txt: "dulden<br>(dulden, duldete, hat geduldet)<br><br>Er duldet es nicht, dass jemand seinen Schreibtisch aufräumt."; tr: "tolerate<br><br>He does not tolerate people cleaning up his desk."; known: false }
    ListElement { txt: "durcheinander<br>(durcheinander)<br><br>Warum sind die ganzen Kleider durcheinander?"; tr: "mixed up, in a mess, chaotic<br><br>Why are all these clothes in such a mess?"; known: false }
    ListElement { txt: "ersetzen<br>(ersetzen, ersetzte, hat ersetzt)<br><br>Leder ist durch kein anderes Material zu ersetzen. Die Versicherung wird den Schaden ersetzen."; tr: "replace<br><br>Leather cannot be replaced by any other material. The insurance will pay compensation for the damages."; known: false }
    ListElement { txt: "fangen<br>(fangen, fing, hat gefangen.)<br><br>Sie hat gestern drei Fische gefangen. Er fing den Ball mit einer Hand."; tr: "catch<br><br>Yesterday she caught three fish. He caught the ball with one hand."; known: false }
    ListElement { txt: "fassen<br>(fassen, fasste, hat gefasst)<br><br>Sie fasste das Kind fest an der Hand. Der Tank fasst über 80 Liter."; tr: "hold<br><br>She held the child firmly by the hand. The tank holds over 80 liters."; known: false }
    ListElement { txt: "festhalten<br>(festhalten, refl. hielt, hat gehalten)<br><br>Bitte halten Sie Ihren Hund fest! Sie hielt an ihrem Plan fest. Bitte halten Sie sich während der Fahrt gut fest."; tr: "hold firm/on<br><br>Please hold on to your dog! She held firm to her plan. Please hold on well during the ride."; known: false }
    ListElement { txt: "finden<br>(finden, fand, hat gefunden)<br><br>Ich kann meine Autoschlüssel nicht finden."; tr: "find<br><br>I cannot find my car keys."; known: false }
    ListElement { txt: "führen<br>(führen, führte, hat geführt)<br><br>Morgen führe ich dich durch die Stadt und zeige dir alles. Seit dem Tode seiner Frau führt er die Firma allein."; tr: "direct, lead, take<br><br>Tomorrow I'll take you around town and show you everything. Since the death of his wife he has directed the company alone."; known: false }
    ListElement { txt: "Führung<br>(die Führung, die Führungen)<br><br>Um 14.00 Uhr gibt es eine Führung durch das Schloss. Er alleine ist für die Führung des Geschäfts verantwortlich."; tr: "guided tour, leadership, running<br><br>At 2 p.m. there is a tour of the castle. He alone is responsible for running the business."; known: false }
    ListElement { txt: "füllen<br>(füllen, füllte, hat gefüllt.)<br><br>Er füllte die Gläser mit Saft."; tr: "fill<br><br>He filled the glasses with juice."; known: false }
    ListElement { txt: "gebrauchen<br>(gebrauchen, gebrauchte, hat gebraucht)<br><br>Wofür gebraucht man das Werkzeug?"; tr: "use<br><br>What do you use the tool for?"; known: false }
    ListElement { txt: "Gebrauch<br>(der Gebrauch, kein Plural)<br><br>Vor dem Gebrauch muss die Flasche geschüttelt werden."; tr: "use<br><br>The bottle has to be shaken before use."; known: false }
    ListElement { txt: "Gewohnheit<br>(die Gewohnheit, die Gewohnheiten)<br><br>Unsere Katze hat die Gewohnheit, im Bücherregal zu schlafen."; tr: "habit<br><br>Our cat has the habit of sleeping in the bookcase."; known: false }
    ListElement { txt: "gießen<br>(gießen, goss, hat gegossen)<br><br>Die Blumen müssen dringend gegossen werden."; tr: "pour, water (plants)<br><br>The flowers have to be watered immediately."; known: false }
    ListElement { txt: "graben<br>(graben, grub, hat gegraben)<br><br>Er ist im Garten und gräbt Löcher für die neuen Bäume."; tr: "dig<br><br>He is in the garden digging holes for the new trees."; known: false }
    ListElement { txt: "halten<br>(halten, hielt, hat gehalten)<br><br>Kannst du bitte kurz die Tasche halten? Ich möchte meine Jacke ausziehen."; tr: "hold<br><br>Can you hold the bag for a moment? I would like to take off my jacket."; known: false }
    ListElement { txt: "heben<br>(heben, hob, hat gehoben)<br><br>Er hob das Kind auf seinen Arm."; tr: "lift, raise<br><br>He lifted the child onto his arm."; known: false }
    ListElement { txt: "hindern<br>(hindern, hinderte, hat gehindert)<br><br>Ich konnte ihn nicht hindern, den Teppich zu kaufen."; tr: "stop, prevent<br><br>I couldn't stop him from buying the carpet."; known: false }
    ListElement { txt: "kaputt<br>(kaputt)<br><br>Das Türschloss ist kaputt."; tr: "broken, busted, damaged, out of order<br><br>The door lock is broken."; known: false }
    ListElement { txt: "kleben<br>(kleben, klebte, hat geklebt)<br><br>Vergiss nicht, eine Briefmarke auf die Karte zu kleben. Die Briefmarke klebt nicht richtig."; tr: "stick, glue<br><br>Don't forget to stick a stamp on the card. The stamp doesn't stick right."; known: false }
    ListElement { txt: "Kontrolle<br>(die Kontrolle, die Kontrollen)<br><br>Fahr langsamer! Hier gibt es oft Geschwindigkeitskontrollen."; tr: "check, inspection, control, checkpoint<br><br>Slow down! They often check the speed here."; known: false }
    ListElement { txt: "kratzen<br>(kratzen, kratzte, hat gekratzt)<br><br>Au, die Katze hat mich gekratzt. Ich habe mich an einem alten Nagel gekratzt."; tr: "scratch<br><br>Ouch, the cat scratched me. I scratched myself on an old nail."; known: false }
    ListElement { txt: "kümmern<br>(kümmern, kümmerte, hat gekümmert)<br><br>Ich kümmere mich um die Heizung, damit sie richtig funktioniert."; tr: "be concerned about, look after, take care of<br><br>I'll take care of the heat, so that it functions properly."; known: false }
    ListElement { txt: "kürzen<br>(kürzen, kürzte, hat gekürzt)<br><br>Der Rock muss gekürzt werden"; tr: "shorten<br><br>The skirt has to be shortened."; known: false }
    ListElement { txt: "lassen<br>(lassen, ließ, hat gelassen)<br><br>Lass das! Ich mag das nicht. Er wurde nicht in Ruhe gelassen. Lass mir das Bild, dann gebe ich dir das andere. Ich habe die Maschine reparieren lassen. Die Sachen lassen sich verbrennen."; tr: "leave, stop, have (done)<br><br>Stop that! I don't like that. He was not left alone. Give me that picture, then I'll give you the other one. I had the machine repaired. The materials can be burned."; known: false }
    ListElement { txt: "legen<br>(legen, legte, hat gelegt)<br><br>Ich habe die Post auf den Schreibtisch gelegt. Der Hund legte sich unter den Tisch."; tr: "lay (down), put<br><br>I put the mail (BE: post) on the desk. The dog lay down under the table."; known: false }
    ListElement { txt: "leihen<br>(leihen, lieh, hat geliehen)<br><br>Ich habe dem Nachbarn die Bohrmaschine geliehen. Ich habe mir eine Bohrmaschine (aus)geliehen."; tr: "lend, loan, borrow<br><br>I lent my neighbor my electric drill. I borrowed an electric drill."; known: false }
    ListElement { txt: "leiten<br>(leiten, leitete, hat geleitet)<br><br>Frau Jensch leitet diese Abteilung. Die Autos wurden über eine Hilfsbrücke geleitet."; tr: "direct, be director/head/boss/ chief/foreman of<br><br>Ms. Jensch is the director of this department. The cars were directed over a temporary bridge."; known: false }
    ListElement { txt: "mahlen<br>(mahlen, mahlte, hat gemahlt)<br><br>Du musst erst Kaffee mahlen."; tr: "grind<br><br>You have to grind the coffee first."; known: false }
    ListElement { txt: "mischen<br>(mischen, mischte, hat gemischt)<br><br>Ich mische den Saft immer mit etwas Wasser."; tr: "mix<br><br>I always mix the juice with some water."; known: false }
    ListElement { txt: "öffnen<br>(öffnen, öffnete, hat geöffnet)<br><br>Öffne bitte die Dose! Wann öffnet die Post? Die Tür öffnet sich automatisch."; tr: "open<br><br>Please open the can (BE: tin). When does the post office open? The door opens automatically."; known: false }
    ListElement { txt: "pflegen<br>(pflegen, pflegte, hat gepflegt)<br><br>Wer pflegt euren kranken Vater? Den Garten pflegt meine Frau."; tr: "take care of<br><br>Who is taking care of your sick father? My wife takes care of the garden."; known: false }
    ListElement { txt: "Pflege<br>(die Pflege, kein Plural)<br><br>Die Pflege des Gartens kostet viel Zeit."; tr: "care<br><br>Taking care of the garden takes a lot of time."; known: false }
    ListElement { txt: "prüfen<br>(prüfen, prüfte, hat geprüft)<br><br>Hast du die Rechnung geprüft?"; tr: "check (over)<br><br>Have you checked the invoice?"; known: false }
    ListElement { txt: "reiben<br>(reiben, rieb, hat gerieben)<br><br>Die Kartoffeln müssen gerieben werden. Der Hund reibt sich sein Fell am Baum."; tr: "rub, grate<br><br>The potatoes have to be grated. The dog is rubbing his fur on the tree."; known: false }
    ListElement { txt: "sammeln<br>(sammeln, sammelte, hat gesammelt)<br><br>Die Pilze habe ich im Wald gesammelt. Er sammelt Briefmarken."; tr: "collect, gather<br><br>I gathered the mushrooms in the forest. He collects stamps."; known: false }
    ListElement { txt: "Sammlung<br>(die Sammlung, die Sammlungen)<br><br>Er besitzt eine wertvolle Bildersammlung."; tr: "collection<br><br>He owns a valuable collection of pictures."; known: false }
    ListElement { txt: "schaffen<br>(schaffen, schaffte, hat geschafft)<br><br>Heute haben wir fast alles geschafft."; tr: "accomplish, manage, get done<br><br>We accomplished almost everything today."; known: false }
    ListElement { txt: "schlagen<br>(schlagen, schlug, hat geschlagen)<br><br>Sie schlug die Tür zu und ging. Er schlug mit der Faust gegen die Tür. Die Kinder schlagen sich."; tr: "hit, slam<br><br>She slammed the door and left. He slammed his fist against the door. The children hit each other."; known: false }
    ListElement { txt: "schließen<br>(schließen, schloss, hat geschlossen)<br><br>Bitte schließen Sie die Tür. Die Tür schließt schlecht. Die Geschäfte schließen um 18.30 Uhr. Abends schließen sich die Blüten dieser Blume."; tr: "close, shut<br><br>Please close the door! The door closes poorly. The stores close at 6:30 p.m. In the evening the blossoms of this flower close up."; known: false }
    ListElement { txt: "schneiden<br>(schneiden, schnitt, hat geschnitten)<br><br>Soll ich den Käse schneiden? Die Schere schneidet gut. Ich habe mich (mir) in den Finger geschnitten."; tr: "cut, slice<br><br>Shall I slice the cheese? The scissors cut well. I cut my finger."; known: false }
    ListElement { txt: "schützen<br>(schützen, + Präp. (vor, gegen))<br><br>Du musst dich besser vor Erkältung schützen. Die Jacke schützt (mich) gut vor Wind."; tr: "protect, guard<br><br>You have to do a better job to protect yourself from colds. The jacket is good protection against the wind."; known: false }
    ListElement { txt: "Schwierigkeit<br>(die Schwierigkeit, die Schwierigkeiten)<br><br>Es gibt noch Schwierigkeiten, aber wir schaffen es trotzdem."; tr: "difficulty<br><br>There are still difficulties, but we'll make it just the same."; known: false }
    ListElement { txt: "stechen<br>(stechen, stach, hat gestochen)<br><br>Ich bin von einer Biene gestochen worden. Vorsicht, die Pflanze sticht!"; tr: "sting, scratch, prick, bite<br><br>I was stung by a bee. Careful, the plant is thorny and will scratch you!"; known: false }
    ListElement { txt: "stecken<br>(stecken, auf) steckte, hat gesteckt)<br><br>Den Ausweis habe ich in deine Handtasche gesteckt."; tr: "stick, place<br><br>I put the I.D. card in your handbag."; known: false }
    ListElement { txt: "stören<br>(stören, störte, hat gestört)<br><br>Sie wurde dauernd durch das Telefon gestört."; tr: "disturb, interrupt<br><br>She was constantly interrupted by the telephone."; known: false }
    ListElement { txt: "stoßen<br>(stoßen, stieß, hat gestoßen)<br><br>Sie stieß ihn in den Rücken. Ich bin mit dem Kopf gegen eine Glastür gestoßen. Ich habe mich am Knie gestoßen."; tr: "hit, bang, push, bump<br><br>She bumped him in the back. I banged my head on a glass door. I banged my knee."; known: false }
    ListElement { txt: "suchen<br>(suchen, suchte, hat gesucht)<br><br>Sie sucht eine neue Stelle. Ich suche meine Brille. Hast du sie gesehen?"; tr: "look for, search<br><br>She's looking for a new job. I'm looking for my glasses. Have you seen them?"; known: false }
    ListElement { txt: "Suche<br>(die Suche, kein Plural)<br><br>Die Suche nach einem Hotelzimmer kostete uns zwei Stunden."; tr: "search, hunt<br><br>The hunt for a hotel room took us two hours,"; known: false }
    ListElement { txt: "treffen<br>(treffen, traf, hat getroffen)<br><br>Er wurde von einem Schlag ins Gesicht getroffen. Ich treffe Uwe morgen. Wir treffen uns jeden Tag."; tr: "hit, meet<br><br>He was hit by a punch in the face. I'm meeting Uwe tomorrow. We meet every day."; known: false }
    ListElement { txt: "trennen<br>(trennen, trennte, hat getrennt)<br><br>Der Fluss trennt die beiden Länder. Es ist besser, wenn wir uns trennen. Sie haben sich vor kurzem getrennt."; tr: "divide, separate, part<br><br>The two countries are divided by the river. It would be better if we parted ways. They separated recently."; known: false }
    ListElement { txt: "Verantwortung<br>(die Verantwortung, kein Plural)<br><br>Sie allein(e) haben die Verantwortung für die Entscheidung."; tr: "responsibility<br><br>You have to bear the responsibility for the decision yourself."; known: false }
    ListElement { txt: "verhindern<br>(verhindern, verhinderte, hat verhindert)<br><br>Den Streit konnte ich nicht verhindern."; tr: "prevent, hinder<br><br>I couldn't prevent the fight."; known: false }
    ListElement { txt: "verlieren<br>(verlieren, verlor, hat verloren)<br><br>Er hat seine Kreditkarte verloren."; tr: "lose<br><br>He lost his credit card."; known: false }
    ListElement { txt: "versorgen<br>(versorgen, versorgte, hat versorgt)<br><br>Mein Mann ist im Stall und versorgt die Tiere."; tr: "take care of/for<br><br>My husband is in the barn/stable caring for the animals."; known: false }
    ListElement { txt: "versprechen<br>(versprechen, versprach, hat versprochen)<br><br>Mir wurde ein höherer Lohn versprachen."; tr: "promise<br><br>I was promised a higher wage."; known: false }
    ListElement { txt: "Versprechen<br>(das Versprechen, die Versprechen)<br><br>Er gab mir das Versprechen, niemandem etwas zu erzählen."; tr: "promise<br><br>He gave me the promise not to tell anyone."; known: false }
    ListElement { txt: "verstecken<br>(verstecken, versteckte, hat versteckt)<br><br>Die Schokolade habe ich vor den Kindern versteckt. Die Katze hat sich auf dem Dachboden versteckt."; tr: "hide<br><br>I hid the chocolate from the children. The cat hid in the attic."; known: false }
    ListElement { txt: "verwenden<br>(verwenden, verwendete, hat verwendet)<br><br>Den Rest des Fleisches verwende ich für das Abendessen."; tr: "use<br><br>I'm going to use the rest of the meat for dinner."; known: false }
    ListElement { txt: "Verwendung<br>(die Verwendung, die Verwendungen)<br><br>Möchtest du das alte Geschirr haben? Ich habe keine Verwendung mehr dafür."; tr: "use<br><br>Would you like to have the old dishes? I have no more use for them."; known: false }
    ListElement { txt: "vorbereiten<br>(vorbereiten, bereitete vor, hat vorbereitet)<br><br>Die Arbeiten müssen gut vorbereitet werden. Er hat sich gut auf die Prüfung vorbereitet."; tr: "prepare<br><br>The work has to be well prepared. He prepared well for the test."; known: false }
    ListElement { txt: "Vorbereitung<br>(die Vorbereitung, die Vorbereitungen)<br><br>Die Vorbereitung für das Fest dauerte drei Tage."; tr: "preparation<br><br>The preparation for the festival lasted three days."; known: false }
    ListElement { txt: "Vorsicht<br>(die Vorsicht, kein Plural)<br><br>Vorsicht! Die Leiter steht nicht fest."; tr: "care, warning, caution<br><br>Be careful! The ladder is not steady."; known: false }
    ListElement { txt: "vorsichtig<br>(vorsichtig)<br><br>Wenn Sie vorsichtig sind, kann Ihnen nichts passieren."; tr: "careful, cautious<br><br>If you are careful, nothing will happen to you."; known: false }
    ListElement { txt: "warnen<br>(warnen, warnte, hat gewarnt)<br><br>Ich habe ihn vor Dieben gewarnt, aber er war trotzdem unvorsichtig."; tr: "warn<br><br>I warned him about thieves, but he was careless just the same."; known: false }
    ListElement { txt: "Warnung<br>(die Warnung, die Warnungen)<br><br>Im Radio habe ich eine Sturmwarnung gehört."; tr: "warning<br><br>I heard a storm warning on the radio."; known: false }
    ListElement { txt: "wechseln<br>(wechseln, wechselte, hat gewechselt)<br><br>Bei dieser Lampe muss die Glühbirne gewechselt werden. Das Wetter wechselt ständig. Könnten Sie mir 100,- DM wechseln?"; tr: "change, replace<br><br>The bulb in this lamp has to be changed. The weather changes all the time. Could you change one hundred Marks for me?"; known: false }
    ListElement { txt: "wickeln<br>(wickeln, wickelte, hat gewickelt)<br><br>Ich muss das Baby noch wickeln. Er wickelt sich einen dicken Schal um den Hals."; tr: "change (diapers; BE: nappies), wrap<br><br>I have to diaper the baby. He wraps a thick shawl around his neck."; known: false }
    ListElement { txt: "wiegen<br>(wiegen, wog, hat gewogen)<br><br>Hast du den Koffer gewogen? Ich bin 1,65 m groß und wiege 55 Kilogramm."; tr: "weigh<br><br>Did you weigh the suitcase? . I am 1.65 meters tall and weigh 55 kilos."; known: false }
    ListElement { txt: "ziehen<br>(ziehen, zog, hat (ist) gezogen)<br><br>Der Wagen wurde von zwei Pferden gezogen."; tr: "pull<br><br>The wagon was pulled by two horses."; known: false }
    ListElement { txt: "zumachen<br>(zumachen, machte zu, hat zugemacht)<br><br>Mach bitte das Fenster zu! Beeil dich, die Geschäfte machen bald zu!"; tr: "close<br><br>Please close the window! Hurry up, the stores/shops are closing soon."; known: false }
    ListElement { txt: "abschalten<br>(abschalten, schaltete ab, hat abgeschaltet)<br><br>Die Elektriker haben den Strom abgeschaltet."; tr: "turn oft<br><br>The electricians turned the power off."; known: false }
    ListElement { txt: "abschneiden<br>(abschneiden, schnitt ab, hat abgeschnitten)<br><br>Wenn die Jeans zu lang sind, kannst du sie unten abschneiden."; tr: "cut oft, shorten<br><br>If the jeans are too long you can shorten them."; known: false }
    ListElement { txt: "anschalten<br>(anschalten, schaltete an, hat angeschaltet)<br><br>Hast du den Backofen schon angeschaltet?"; tr: "turn in, switch on<br><br>Have you already turned on the oven?"; known: false }
    ListElement { txt: "anzünden<br>(anzünden, zündete an, hat angezündet)<br><br>Die Leute glauben, dass er sein Haus selbst angezündet hat."; tr: "set on fire<br><br>They think he set his house on fire himself."; known: false }
    ListElement { txt: "aufbauen<br>(aufbauen, baute auf, hat aufgebaut)<br><br>Das Rathaus wurde nach dem Krieg neu aufgebaut."; tr: "build, rebuild<br><br>After the war the city hall was rebuilt."; known: false }
    ListElement { txt: "aufgeben<br>(aufgeben, gab auf, hat aufgegeben)<br><br>Gib bitte den Brief bei der Post auf! Der Läufer gab erschöpft auf."; tr: "deliver, give up<br><br>Deliver the letter to the post office. The runner gave up, exhausted."; known: false }
    ListElement { txt: "aufheben<br>(aufheben, hob auf, hat aufgehoben)<br><br>Die Rechnungen müssen 10 Jahre aufgehoben werden. Er hob seinen Mantel vom Boden auf."; tr: "keep, save, pick up<br><br>The receipts must be kept for 10 years. He picked his coat up off the floor."; known: false }
    ListElement { txt: "aufmachen<br>(aufmachen, machte auf, hat aufgemacht)<br><br>Machst du bitte die Flasche auf? Wann macht der Supermarkt auf?"; tr: "open<br><br>Would you please open the bottle? When does the supermarket open?"; known: false }
    ListElement { txt: "aufstellen<br>(aufstellen, stellte auf, hat aufgestellt)<br><br>Die Stühle sollen in einer Reihe aufgestellt werden. Wir hatten das Zeit direkt am Strand aufgestellt."; tr: "set up, stand/put up, place<br><br>The chairs should be placed in a row. We put the tent up right on the beach."; known: false }
    ListElement { txt: "auseinander nehmen<br>(auseinander nehmen, nahm auseinander, hat auseinander genommen)<br><br>Den Schrank kann man ganz auseinander nehmen."; tr: "take apart, dismantle<br><br>The cabinet can be completely taken apart."; known: false }
    ListElement { txt: "ausschalten<br>(ausschalten, schaltete aus, hat ausgeschaltet)<br><br>Hast du die Heizung ausgeschaltet?"; tr: "turn off<br><br>Did you turn off the heat(er)?"; known: false }
    ListElement { txt: "beaufsichtigen<br>(beaufsichtigen, beaufsichtigte, hat beaufsichtigt)<br><br>Die Kinder werden morgens von ihrer Oma beaufsichtigt."; tr: "take care of, watch, (baby)sit<br><br>In the morning the children are taken care of by their grandmother."; known: false }
    ListElement { txt: "bedecken<br>(bedecken, bedeckte, hat bedeckt)<br><br>Das Tischtuch bedeckt nicht den ganzen Tisch."; tr: "cover<br><br>The tablecloth doesn't cover the whole table."; known: false }
    ListElement { txt: "befestigen<br>(befestigen, befestigte, hat befestigt)<br><br>An dieser Wand lässt sich kein Regal befestigen."; tr: "attach, fasten<br><br>No shelf can be attached to this wall."; known: false }
    ListElement { txt: "beherrschen<br>(beherrschen, beherrschte, hat beherrscht)<br><br>Das Land wird von einem König beherrscht. Welche Fremdsprachen beherrschen Sie? Bitte bleib ruhig und beherrsch dich!"; tr: "control, rule, know well<br><br>The country is ruled by a king. Which foreign languages do you know well? Please be calm and control yourself."; known: false }
    ListElement { txt: "berücksichtigen<br>(berücksichtigen, berücksichtigte, hat berücksichtigt)<br><br>Sie braucht noch viel Ruhe. Man muss berücksichtigen, dass sie sehr krank war."; tr: "consider, remember<br><br>She still needs a lot of rest. You have to consider that she was very ill."; known: false }
    ListElement { txt: "Berührung<br>(die Berührung, die Berührungen)<br><br>Er hat seine Hand verbrannt. Jede Berührung tut weh."; tr: "touch, physical contact<br><br>He burned his hand. The slightest touch hurts."; known: false }
    ListElement { txt: "beschädigen<br>(beschädigen, beschädigte, hat beschädigt)<br><br>Das Hoftor ist beschädigt worden."; tr: "damage<br><br>The door to the courtyard was damaged."; known: false }
    ListElement { txt: "beseitigen<br>(beseitigen, beseitigte, hat beseitigt)<br><br>Nach dem Picknick haben wir alle Abfälle beseitigt."; tr: "throwaway, get rid of, clean up<br><br>After the picnic we cleaned up all the trash."; known: false }
    ListElement { txt: "betreuen<br>(betreuen, betreute, hat betreut)<br><br>Meine Mutter betreut unser Haus, wenn wir längere Zeit nicht da sind."; tr: "take care of, watch<br><br>My mother takes care of our house when we're gone for an extended period of time."; known: false }
    ListElement { txt: "bewähren<br>(bewähren, bewährte, hat bewährt)<br><br>Unsere Waschmaschine hat sich bewährt, sie ist schon 12 Jahre alt und läuft noch gut."; tr: "be worth it, prove worthwhile<br><br>Our washer was worth it; it is already 12 years old and still runs well."; known: false }
    ListElement { txt: "bilden<br>(bilden, bildete, hat gebildet)<br><br>Die Kinder bildeten einen Kreis. Auf dem Wasser bildete sich verdächtiger Schaum."; tr: "form<br><br>The children formed a circle. On the water a curious foam formed."; known: false }
    ListElement { txt: "blasen<br>(blasen, blies, hat geblasen)<br><br>Die Maschine bläst frische Luft in den Tunnel. Der Wind bläst mir ins Gesicht."; tr: "blow<br><br>The machine blows fresh air into the tunnel. Wind is blowing in my face."; known: false }
    ListElement { txt: "einbeziehen<br>(einbeziehen, bezog ein, hat einbezogen)<br><br>Das Problem lässt sich nur gemeinsam lösen, deshalb müssen alle in die Diskussion einbezogen werden."; tr: "include<br><br>The problem can only be solved together; so everybody has to be included in the discussion."; known: false }
    ListElement { txt: "einschalten<br>(einschalten, schaltete ein, hat eingeschaltet)<br><br>Wer hat das Radio eingeschaltet?"; tr: "turn on<br><br>Who turned on the radio?"; known: false }
    ListElement { txt: "entfernen<br>(entfernen, entfernte, hat entfernt)<br><br>Diese Flecken lassen sich nicht entfernen."; tr: "remove<br><br>These spots cannot be removed."; known: false }
    ListElement { txt: "enthalten<br>(enthalten, enthielt, hat enthalten)<br><br>Wie viel Stück enthält die Packung?"; tr: "contain, hold<br><br>How many items are in this package?"; known: false }
    ListElement { txt: "erhöhen<br>(erhöhen, erhöhte, hat erhöht)<br><br>Die Postgebühren wurden erhöht."; tr: "raise<br><br>Postal fees were raised."; known: false }
    ListElement { txt: "Erhöhung<br>(die Erhöhung, die Erhöhungen)<br><br>Die Erhöhung der Benzinpreise wurde zurückgenommen."; tr: " increase<br><br>The price increase for gasoline was rescinded."; known: false }
    ListElement { txt: "ermöglichen<br>(ermöglichen, ermöglichte, hat ermöglicht)<br><br>Der neue Motor ermöglicht eine höhere Geschwindigkeit."; tr: "make possible, enable<br><br>The new molar makes a higher speed possible."; known: false }
    ListElement { txt: "erreichen<br>(erreichen, erreichte, hat erreicht)<br><br>Das oberste Fach kann ich mit der Hand nicht erreichen. Sie können mich unter dieser Nummer erreichen. Hast du erreicht, was du wolltest? Beeil dich, sonst erreichst du den Bus nicht mehr!"; tr: "reach, attain, get, get to<br><br>I can't reach the top shelf. You can reach me at this number. Did you get what you wanted? Hurry, or you won't get to the bus on time!"; known: false }
    ListElement { txt: "erwischen<br>(erwischen, erwischte, hat erwischt)<br><br>Der Dieb wurde erwischt. Hast du den Zug noch erwischt? Ich habe noch einen Pullover erwischt. Sonst waren fast alle verkauft."; tr: "catch, get<br><br>The thief was caught. Did you still make your train? I managed to still get a sweater. Most of them were already sold."; known: false }
    ListElement { txt: "falten<br>(falten, faltete, hat gefaltet)<br><br>Er faltete die Zeitung und steckte sie in seine Tasche."; tr: "fold<br><br>He folded the newspaper and stuck it in his briefcase/bag."; known: false }
    ListElement { txt: "festmachen<br>(festmachen, machte fest, hat festgemacht)<br><br>Die Bretter kann man so nicht festmachen."; tr: "attach, to fix on<br><br>You can't attach the boards like that."; known: false }
    ListElement { txt: "fördern<br>(fördern, förderte, hat gefördert)<br><br>Durch mehr Werbung soll der Verkauf gefördert werden."; tr: "promote, increase<br><br>Sales should increase with more advertising."; known: false }
    ListElement { txt: "Förderung<br>(die Förderung, kein Plural)<br><br>Es gibt an unserer Schule jetzt Kurse zur Förderung der schlechteren Schüler."; tr: "assistance, support, help, aid<br><br>At our school there are courses to help weak students."; known: false }
    ListElement { txt: "Gestaltung<br>(die Gestaltung, die Gestaltungen)<br><br>Die Gestaltung des Gartens ist wirklich schön."; tr: "arrangement, design<br><br>The arrangement of the garden is very nice."; known: false }
    ListElement { txt: "heimlich<br>(heimlich)<br><br>Die Schüler rauchen heimlich auf den Toiletten."; tr: "secret, in secret<br><br>Students smoke in secret in the lavatories."; known: false }
    ListElement { txt: "hinzufügen<br>(hinzufügen, fügte hinzu, hat hinzugefügt)<br><br>Die Soße schmeckt gut, vielleicht solltest du noch etwas Sahne hinzufügen."; tr: "add<br><br>The sauce tastes good; perhaps you should add a little cream."; known: false }
    ListElement { txt: "klopfen<br>(klopfen, klopfte, hat geklopft)<br><br>Hörst du? Jemand klopft an die Tür,"; tr: "knack<br><br>Did you hear that? Someone is knocking at the door."; known: false }
    ListElement { txt: "läuten<br>(läuten, läutete, hat geläutet)<br><br>Es läutet. Machst du bitte die Tür auf?"; tr: "ring (bells)<br><br>The doorbell rang. Would you please open the door?"; known: false }
    ListElement { txt: "lösen<br>(lösen, löste, hat gelöst)<br><br>Der Knoten ist zu fest, ich kann ihn nicht lösen."; tr: "loosen<br><br>The knot is too tight; I can't loosen it."; known: false }
    ListElement { txt: "nachgeben<br>(nachgeben, gab nach, hat nachgegeben)<br><br>Sie verteidigte ihre Rechte und gab nicht nach."; tr: "give in<br><br>She defended her rights and did not give in."; known: false }
    ListElement { txt: "nähen<br>(nähen, nähte, hat genäht)<br><br>Sie näht alle ihre Kleider selbst."; tr: "sew<br><br>She sews all her own clothes."; known: false }
    ListElement { txt: "regeln<br>(regeln, regelte, hat geregelt)<br><br>Diese Sache muss schnell geregelt werden."; tr: "regulate, settle<br><br>The matter must be settled quickly."; known: false }
    ListElement { txt: "reißen<br>(reißen, riss, hat (ist) gerissen)<br><br>Der Sturm riss das Zelt um. Der Dieb hat ihr die Tasche weggerissen. Achtung, das Seil reißt!"; tr: "tear, rip<br><br>The storm knocked down the tent. The thief ripped off her purse. Look out, the rope is tearing!"; known: false }
    ListElement { txt: "rühren<br>(rühren, rührte, hat gerührt)<br><br>Vorsicht, die Farbe muss vor dem Gebrauch gut gerührt werden!"; tr: "stir, mix<br><br>Careful, the paint has to be stirred well before using it."; known: false }
    ListElement { txt: "sägen<br>(sägen, sägte, hat gesägt)<br><br>Er hat das Holz mit der Hand gesägt, nicht mit der Maschine."; tr: "saw<br><br>He sawed the wood by hand, not with a machine."; known: false }
    ListElement { txt: "schimpfen<br>(schimpfen, schimpfte, hat geschimpft)<br><br>Der Gast schimpfte über den schlechten Service im Restaurant."; tr: "complain (about), tell off<br><br>The guest complained about the poor service in the restaurant."; known: false }
    ListElement { txt: "senken<br>(senken, senkte, hat gesenkt)<br><br>Der Kran senkte das Boot ins Wasser."; tr: "lower<br><br>The crane lowered the boat into the water."; known: false }
    ListElement { txt: "steigern<br>(steigern, steigerte, hat gesteigert)<br><br>Der Zug steigerte seine Geschwindigkeit immer mehr."; tr: "increase<br><br>The train increased its speed more and more."; known: false }
    ListElement { txt: "Störung<br>(die Störung, die Störungen)<br><br>Entschuldigen Sie bitte die Störung. Wegen einer Störung konnte er kein Fernsehbild empfangen."; tr: "disturbance<br><br>Please excuse the disturbance. Because of an interference he could not get the television picture."; known: false }
    ListElement { txt: "streichen<br>(streichen, strich, hat gestrichen)<br><br>Die Fenster müssen gestrichen werden."; tr: "paint<br><br>The windows have to be painted."; known: false }
    ListElement { txt: "stützen<br>(stützen, stützte, hat gestützt)<br><br>Die Äste des Apfelbaumes müssen gestützt werden. Er stützt sich auf einen Stock."; tr: "support<br><br>The branches of the apple tree have to be supported. He supports himself with a cane."; known: false }
    ListElement { txt: "Trennung<br>(die Trennung, die Trennungen)<br><br>Die Trennung von seiner Familie machte ihn sehr traurig."; tr: "separation<br><br>The separation from his family made him very sad."; known: false }
    ListElement { txt: "trocknen<br>(trocknen, trocknete, hat getrocknet)<br><br>Du musst noch deine Haare trocknen. Die Farbe trocknet schnell."; tr: "dry<br><br>You still have to dry your hair. The paint dries quickly."; known: false }
    ListElement { txt: "überprüfen<br>(überprüfen, überprüfte, hat überprüft)<br><br>Das kann nicht stimmen. Bitte überprüfen Sie die Rechnung noch einmal!"; tr: "check (over)<br><br>That can't be right. Please check the bill again!"; known: false }
    ListElement { txt: "Überprüfung<br>(die Überprüfung, die Überprüfungen)<br><br>Bei der Überprüfung der Rechnung wurden einige Fehler festgestellt."; tr: "check(ing)<br><br>Checking the bill they found a number of errors."; known: false }
    ListElement { txt: "überraschen<br>(überraschen, überraschte, hat überrascht)<br><br>Wir waren überrascht, dass wir nicht kontrolliert wurden. Ich überraschte meine Tochter, als sie heimlich eine Zigarette rauchte."; tr: "surprise<br><br>We were surprised that we were not checked. I surprised my daughter smoking a cigarette secretly."; known: false }
    ListElement { txt: "Überraschung<br>(die Überraschung, die Überraschungen)<br><br>Ich habe eine große Überraschung für dich."; tr: "surprise<br><br>I have a big surprise far you."; known: false }
    ListElement { txt: "übersehen<br>(übersehen, übersah, hat übersehen)<br><br>Du hast übersehen, dass die Ampel rot war."; tr: "overlook, neglect<br><br>You overlooked the red (traffic) light."; known: false }
    ListElement { txt: "umgehen<br>(umgehen, umging, hat umgangen)<br><br>Diese Vorschrift kann man nicht ohne weiteres umgehen."; tr: "bypass, disregard<br><br>You cannot disregard the regulation without consequences."; known: false }
    ListElement { txt: "umgehen<br>(umgehen, ging um, ist umgegangen)<br><br>Sie kann sehr gut mit Pferden umgehen."; tr: "work, handle, deal with<br><br>She can work well with horses."; known: false }
    ListElement { txt: "umrühren<br>(umrühren, rührte um, hat umgerührt)<br><br>Die Suppe muss ständig umgerührt werden."; tr: "stir<br><br>The soup has to be stirred constantly."; known: false }
    ListElement { txt: "unterbrechen<br>(unterbrechen, unterbrach, hat (ist) unterbrochen)<br><br>Plötzlich war das Telefongespräch unterbrochen."; tr: "interrupt<br><br>Suddenly the phone call was interrupted."; known: false }
    ListElement { txt: "unterlassen<br>(unterlassen, unterließ, hat unterlassen)<br><br>Unterlassen Sie die laute Musik, sonst werde ich mich beschweren!"; tr: "stop<br><br>Stop (playing) the loud music or I'll complain!"; known: false }
    ListElement { txt: "unterstützen<br>(unterstützen, unterstützte, hat unterstützt)<br><br>Gerd muss seine Eltern unterstützen, weil sie zu wenig Rente bekommen."; tr: "support<br><br>Gerd has to support his parents because their pension is too small."; known: false }
    ListElement { txt: "Unterstützung<br>(die Unterstützung, die Unterstützungen)<br><br>Er bat um Unterstützung für seinen Plan."; tr: "support<br><br>He asked for support for his plan."; known: false }
    ListElement { txt: "unvorsichtig<br>(unvorsichtig)<br><br>Er ist ein unvorsichtiger Fahrer, er fährt so wild."; tr: "careless<br><br>He is a careless driver; he drives wildly."; known: false }
    ListElement { txt: "verbergen<br>(verbergen, verbarg, hat verborgen)<br><br>Verbirgst du ein Geheimnis vor mir? Die Tiere verbargen sich bis zum Abend im Wald."; tr: "hide<br><br>Are you hiding a secret from me? The animals hid in the forest until evening."; known: false }
    ListElement { txt: "verbessern<br>(verbessern, verbesserte, hat verbessert)<br><br>Die Fehler habe ich alle verbessert. Die Qualität der Produkte hat sich im letzten Jahr verbessert."; tr: "improve, make better, correct (mistakes)<br><br>I have corrected all the mistakes. The quality of the products improved last year."; known: false }
    ListElement { txt: "verbinden<br>(verbinden, verband, hat verbunden)<br><br>Der Kanal verbindet zwei Flüsse. Dieser Plan ist mit sehr viel Arbeit verbunden."; tr: "join, connect<br><br>The canal connects two rivers. This plan requires (lit.: is connected with) a lot of work."; known: false }
    ListElement { txt: "verbrennen<br>(verbrennen, verbrannte, hat (ist) verbrannt)<br><br>Nach einem Streit hat sie alle Briefe von ihm verbrannt."; tr: "burn<br><br>After an argument she burned all his letters."; known: false }
    ListElement { txt: "vergießen<br>(vergießen, vergoss, hat vergossen)<br><br>Woher kommt der Fleck auf dem Tisch? Monika hat Kaffee vergossen."; tr: "spill<br><br>What caused the stain on the table? Monika spilled coffee."; known: false }
    ListElement { txt: "vermitteln<br>(vermitteln, vermittelte, hat vermittelt)<br><br>Sie hat ihm eine Stelle vermittelt."; tr: "provide, help to get, mediate<br><br>She helped him get a job."; known: false }
    ListElement { txt: "vernachlässigen<br>(vernachlässigen, vernachlässigte, hat vernachlässigt)<br><br>Ich finde, dass du deinen Hund vernachlässigst."; tr: "neglect<br><br>I think you're neglecting your dog."; known: false }
    ListElement { txt: "versäumen<br>(versäumen, versäumte, hat versäumt)<br><br>Diese Chance hast du leider versäumt."; tr: "pass up, miss<br><br>You have unfortunately passed up this chance."; known: false }
    ListElement { txt: "verstärken<br>(verstärken, verstärkte, hat verstärkt)<br><br>Die Wand muss verstärkt werden, sonst stürzt das Haus ein. Die Fußballmannschaft verstärkte sich mit einem neuen Spieler."; tr: "strengthen, reinforce<br><br>The wall has to be strengthened; otherwise the house will cave in. The soccer (BE: football) team was reinforced with a new player."; known: false }
    ListElement { txt: "verwandeln<br>(verwandeln, verwandelte, hat verwandelt)<br><br>Das alte Haus wurde fast in einen Neubau verwandelt. Seit ihrer Krankheit hat sie sich vollkommen verwandelt."; tr: "transform, change<br><br>The old house was almost transformed into a new building. Since her illness she has changed completely."; known: false }
    ListElement { txt: "verwirklichen<br>(verwirklichen, verwirklichte, hat verwirklicht)<br><br>Er hat gute Ideen, aber er kann sie nicht verwirklichen."; tr: "realize, accomplish<br><br>He has good ideas, but he cannot realize them."; known: false }
    ListElement { txt: "Verwirklichung<br>(die Verwirklichung, die Verwirklichungen)<br><br>Die Reise war für ihn die Verwirklichung eines Traums."; tr: "realization, accomplishment<br><br>The trip was the realization of a dream for him."; known: false }
    ListElement { txt: "verwöhnen<br>(verwöhnen, verwöhnte, hat verwöhnt)<br><br>Sie verwöhnt ihre Katze."; tr: "spoil (a personality)<br><br>She spoils her cat."; known: false }
    ListElement { txt: "wagen<br>(wagen, wagte, hat gewagt)<br><br>Er wagt nicht, ihr zu widersprechen. Sie wagt sich nachts nicht allein durch den Park."; tr: "dare<br><br>He doesn't dare to contradict her. She does not dare to walk through the park alone at night."; known: false }
    ListElement { txt: "wehren<br>(wehren, wehrte, hat gewehrt)<br><br>Er wehrte sich gegen die Vorwürfe."; tr: "defend<br><br>He defended himself against the accusations."; known: false }
    ListElement { txt: "zerbrechen<br>(zerbrechen, zerbrach, hat (ist) zerbrochen)<br><br>Wer hat das Glas zerbrochen? Niemand, es st in der Spülmaschine von selbst zerbrochen."; tr: "break, shatter<br><br>Who broke the glass? Nobody; it shattered by itself in the dishwasher."; known: false }
    ListElement { txt: "zerreißen<br>(zerreißen, zerriss, hat zerrissen)<br><br>Die unscharfen Fotos kannst du zerreißen und wegwerfen."; tr: "tear up<br><br>You can tear up and throwaway the photos that are out-of-focus."; known: false }
    ListElement { txt: "zudecken<br>(zudecken, deckte zu, hat zugedeckt)<br><br>Er deckte das schlafende Kind zu."; tr: "cover (up)<br><br>He covered the sleeping child."; known: false }
    ListElement { txt: "zulassen<br>(zulassen, ließ zu, hat zugelassen)<br><br>Ausnahmen werden nicht zugelassen!"; tr: "permit<br><br>Exceptions are not permitted!"; known: false }
    ListElement { txt: "zusammenlegen<br>(zusammenlegen, legte zusammen, hat zusammengelegt)<br><br>Leg den Pullover zusammen und dann in den Schrank!"; tr: "fold, put together<br><br>Fold up the sweater and put it in the dresser."; known: false }

}

