import QtQuick 2.2

ListModel {
    property string name: "02.8_Learning_and_Knowledge"
    ListElement { txt: "aufschreiben<br>(aufschreiben, schrieb auf, hat aufgeschrieben)<br><br>Das muss ich (mir) aufschreiben, damit ich es nicht vergesse."; tr: "write down, write someone a note<br><br>I have to write this down so that I won't forget it."; known: false }
    ListElement { txt: "bedeuten<br>(bedeuten, bedeutete, hat bedeutet)<br><br>Was bedeutet dieses Wort?"; tr: "mean, signify<br><br>What does this word mean?"; known: false }
    ListElement { txt: "Bedeutung<br>(die Bedeutung, die Bedeutungen)<br><br>Dieses Wort hat mehrere Bedeutungen."; tr: "meaning, significance<br><br>This word has several meanings."; known: false }
    ListElement { txt: "Begabung<br>(die Begabung, die Begabungen)<br><br>Sie malt gerne, aber ich finde, sie hat keine besondere Begabung dafür."; tr: "talent<br><br>She likes to paint, but I don't think she has any special talent for it."; known: false }
    ListElement { txt: "Begriff<br>(der Begriff, die Begriffe)<br><br>Mein Arzt verwendet oft medizinische Begriffe, die ich nicht verstehe."; tr: "concept, term, idea<br><br>My doctor often uses medical terms that I do not understand."; known: false }
    ListElement { txt: "Beispiel<br>(das Beispiel, die Beispiele)<br><br>Er erklärte das Problem anhand eines Beispiels."; tr: "example<br><br>He explained the problem using an example."; known: false }
    ListElement { txt: "Bibliothek<br>(die Bibliothek, die Bibliotheken)<br><br>Das Buch habe ich in der Bibliothek ausgeliehen."; tr: "library<br><br>I borrowed the book from the library."; known: false }
    ListElement { txt: "Bildung<br>(die Bildung, kein Plural)<br><br>Er ist nicht dumm, aber ihm fehlt eine allgemeine Bildung."; tr: "education<br><br>He is not stupid, but he lacks a general education."; known: false }
    ListElement { txt: "Buch<br>(das Buch, die Bücher)<br><br>Ich lese gerade ein interessantes Buch."; tr: "book<br><br>I'm reading an interesting book."; known: false }
    ListElement { txt: "Buchstabe<br>(der Buchstabe, die Buchstaben)<br><br>Das Wort hat neun Buchstaben."; tr: "letter (of the alphabet)<br><br>The word has nine letters."; known: false }
    ListElement { txt: "Fach<br>(das Fach, die Fächer)<br><br>Sie weiß noch nicht, welches Fach sie studieren möchte."; tr: "subject (academic)<br><br>She does not yet know which subject she would like to study."; known: false }
    ListElement { txt: "Forschung<br>(die Forschung, die Forschungen)<br><br>Die medizinische Forschung hat noch kein Mittel gegen Krebs gefunden."; tr: "research<br><br>Medical research has yet to find a cure for cancer."; known: false }
    ListElement { txt: "Fortschritt<br>(der Fortschritt, die Fortschritte)<br><br>Sie macht beim Lernen gute Fortschritte."; tr: "progress<br><br>She is making good progress in her studies."; known: false }
    ListElement { txt: "fähig<br>(fähig)<br><br>Mit 80 Jahren ist er noch fähig, Gartenarbeit zu machen."; tr: "capable, able<br><br>At age 80 he is still capable of working in the garden."; known: false }
    ListElement { txt: "Fähigkeit<br>(die Fähigkeit, die Fähigkeiten)<br><br>Sie hat angeblich die Fähigkeit, die Zukunft vorauszusagen."; tr: "capability, ability<br><br>She supposedly has the ability to predict the future."; known: false }
    ListElement { txt: "Germanistik<br>(die Germanistik, kein Plural)<br><br>In Japan und Korea hat die Germanistik eine lange Tradition."; tr: "German language and literature, Germanistics, German<br><br>In Japan and Korea the study of German language and literature enjoys a long tradition."; known: false }
    ListElement { txt: "Geschichte<br>(die Geschichte, kein Plural)<br><br>Er studierte Deutsch und Geschichte."; tr: "history, story<br><br>He is studying German and history."; known: false }
    ListElement { txt: "geschichtlich<br>(geschichtlich)<br><br>Unser geschichtliches Wissen über die Steinzeit ist sehr gering."; tr: "historical<br><br>Our historical knowledge about the Stone Age is very limited."; known: false }
    ListElement { txt: "Korrektur<br>(die Korrektur, die Korrekturen)<br><br>Bei der Korrektur des Briefes habe ich keine Fehler entdeckt."; tr: "correction<br><br>When I corrected the letter, found no mistakes."; known: false }
    ListElement { txt: "korrigieren<br>(korrigieren, korrigierte, hat korrigiert)<br><br>Bitte korrigieren Sie den Brief und bringen Sie ihn dann zur Post."; tr: "correct<br><br>Please correct the letter and then take it to the post office."; known: false }
    ListElement { txt: "lehren<br>(lehren, lehrte, hat gelehrt)<br><br>Sie lehrt Physik an der Universität."; tr: "teach (at a university or college)<br><br>She teaches physics at the university. ­­­"; known: false }
    ListElement { txt: "Lehrer<br>(der Lehrer, die Lehrer)<br><br>Er ist ein sehr guter Lehrer. Die Schüler mögen ihn."; tr: "teacher, instructor<br><br>He is a very good teacher. The students like him."; known: false }
    ListElement { txt: "lernen<br>(lernen, lernte, hat gelernt)<br><br>Sie hat in der Schule Spanisch gelernt."; tr: "learn<br><br>She learned Spanish in school."; known: false }
    ListElement { txt: "lesen<br>(lesen, las, hat gelesen)<br><br>Er liest gerade Zeitung."; tr: "read<br><br>He is reading the newspaper."; known: false }
    ListElement { txt: "Methode<br>(die Methode, die Methoden)<br><br>Es gibt verschiedene Methoden, eine Sprache zu lernen."; tr: "method<br><br>There are different methods for learning a language."; known: false }
    ListElement { txt: "Naturwissenschaft<br>(die Naturwissenschaft, die Naturwissenschaften)<br><br>Mein Bruder interessiert sich für Naturwissenschaft."; tr: "(natural) science<br><br>My brother is interested in science."; known: false }
    ListElement { txt: "Probe<br>(die Probe, die Proben)<br><br>Nach der Probezeit wurde er fest angestellt."; tr: "trial, probation, sample<br><br>After the probationary period he was hired full time."; known: false }
    ListElement { txt: "rechnen<br>(rechnen, rechnete, hat gerechnet)<br><br>Diese Aufgabe kann ich nicht im Kopf rechnen. Sie kann schnell rechnen."; tr: "calculate, figure<br><br>I cannot figure the problem in my head. She can calculate quickly."; known: false }
    ListElement { txt: "Rechnung<br>(die Rechnung, die Rechnungen)<br><br>Komplizierte Rechnungen mache ich mit dem Taschenrechner."; tr: "invoice, bill, check, calculation<br><br>Complicated calculations I do with a calculator."; known: false }
    ListElement { txt: "schwer<br>(schwer)<br><br>Deutsch gilt als schwere Sprache."; tr: "heavy, difficult, complicated, hard<br><br>German is considered to be a difficult language."; known: false }
    ListElement { txt: "schwierig<br>(schwierig)<br><br>Die meisten Prüfungsfragen waren nicht schwierig."; tr: "difficult, complicated, hard<br><br>Most of the examination questions were not difficult."; known: false }
    ListElement { txt: "Seite<br>(die Seite, die Seiten)<br><br>Das Buch hat 251 Seiten."; tr: "page, side<br><br>The book has 251 pages."; known: false }
    ListElement { txt: "Theorie<br>(die Theorie, die Theorien)<br><br>Über die Entstehung der Erde gibt es verschiedene Theorien."; tr: "theory<br><br>There are various theories about the origin of the earth. "; known: false }
    ListElement { txt: "wissen<br>(wissen, wusste, hat gewusst)<br><br>Ich weiß nicht, wo er wohnt."; tr: "know<br><br>I do not know where he lives."; known: false }
    ListElement { txt: "Wissen<br>(das Wissen, kein Plural)<br><br>Sie hat auf diesem Gebiet ein großes Wissen."; tr: "knowledge<br><br>She has considerable knowledge in this area."; known: false }
    ListElement { txt: "Wissenschaft<br>(die Wissenschaft, die Wissenschaften)<br><br>Philosophie ist die älteste Wissenschaft."; tr: "(branch of) knowledge, academic subject, science<br><br>Philosophy is the oldest branch of knowledge."; known: false }
    ListElement { txt: "Wissenschaftler<br>(der Wissenschaftler, die Wissenschaftler)<br><br>An unserem Institut arbeiten sechs Wissenschaftler und Wissenschaftlerinnen."; tr: "scientist, researcher<br><br>There are six researchers working at our institute."; known: false }
    ListElement { txt: "wissenschaftlich<br>(wissenschaftlich)<br><br>Über die Ursachen von Krebs gibt es viele wissenschaftliche Untersuchungen."; tr: "scientific<br><br>There have been many scientific studies on the causes of cancer."; known: false }
    ListElement { txt: "Zeichen<br>(das Zeichen, die Zeichen)<br><br>$' ist das Zeichen für Dollar."; tr: "sign, symbol<br><br>&quot;$&quot; is the symbol for dollar."; known: false }
    ListElement { txt: "Zeile<br>(die Zeile, die Zeilen)<br><br>Das Gedicht hat sieben Zeilen."; tr: "line (in a text)<br><br>The poem has seven lines."; known: false }
    ListElement { txt: "Überlegung<br>(die Überlegung, die Überlegungen)<br><br>Er hat ohne Überlegung gehandelt."; tr: "thinking, planning, forethought, consideration<br><br>He acted without thinking."; known: false }
    ListElement { txt: "Band<br>(der Band, die Bände)<br><br>Dieses Lexikon besteht aus fünf Bänden."; tr: "volume<br><br>This encyclopedia consists of five volumes."; known: false }
    ListElement { txt: "besichtigen<br>(besichtigen, besichtigte, hat besichtigt)<br><br>Das Museum kann man nur vormittags besichtigen."; tr: "view, visit (museums, ruins, etc.)<br><br>You can visit the museum only in the morning."; known: false }
    ListElement { txt: "Biologie<br>(die Biologie, kein Plural)<br><br>Sie studiert im 3. Semester Biologie."; tr: "biology<br><br>She is in her third semester in biology."; known: false }
    ListElement { txt: "Blatt<br>(das Blatt, die die Blätter)<br><br>Kannst du mir bitte ein Blatt Papier geben?"; tr: "piece, sheet (of paper)<br><br>Could you please give me a piece of paper?"; known: false }
    ListElement { txt: "Block<br>(der Block, die die Blöcke)<br><br>Bringe mir bitte einen Block Papier aus dem Schreibwarengeschäft mit."; tr: "pad (of paper), block<br><br>Please bring me a pad of paper from the stationery store."; known: false }
    ListElement { txt: "Buchhandlung<br>(die Buchhandlung, die Buchhandlungen)<br><br>In dieser Buchhandlung kann man auch Zeitschriften kaufen."; tr: "bookstore, bookshop<br><br>You can also buy magazines in this bookstore."; known: false }
    ListElement { txt: "Bücherei<br>(die Bücherei, die Büchereien)<br><br>Das Buch habe ich in der Stadtbücherei ausgeliehen."; tr: "library<br><br>I borrowed the book from the municipal library."; known: false }
    ListElement { txt: "Chemie<br>(die Chemie, kein Plural)<br><br>In der Schule war Chemie mein Lieblingsfach."; tr: "chemistry<br><br>Chemistry was my favorite subject in school."; known: false }
    ListElement { txt: "chemisch<br>(chemisch)<br><br>H20 ist die chemische Formel für Wasser."; tr: "chemical<br><br>H20 is the chemical formula for water."; known: false }
    ListElement { txt: "entdecken<br>(entdecken, entdeckte, hat entdeckt)<br><br>1492 hat Kolumbus Amerika entdeckt."; tr: "discover<br><br>Columbus discovered America in 1492."; known: false }
    ListElement { txt: "Entdeckung<br>(die Entdeckung, die Entdeckungen)<br><br>Das 15. Jahrhundert war das Zeitalter der großen Entdeckungsreisen."; tr: "discovery<br><br>The fifteenth century was the age of the great journeys of discovery."; known: false }
    ListElement { txt: "Erdkunde<br>(die Erdkunde, kein Plural)<br><br>Er ist Lehrer für Deutsch und Erdkunde."; tr: "geography (as an academic subject)<br><br>He is a teacher of German and geography"; known: false }
    ListElement { txt: "Erforschung<br>(die Erforschung, die Erforschungen)<br><br>Bei der Erforschung der Höhle wurden Zeichnungen aus der Steinzeit entdeckt."; tr: "research(ing)<br><br>While researching the cave they discovered drawings from the Stone Age."; known: false }
    ListElement { txt: "Fachmann<br>(der Fachmann, die Fachmänner)<br><br>Diese Arbeit muss von einem Fachmann gemacht werden."; tr: "expert<br><br>This work has to be done by an expert."; known: false }
    ListElement { txt: "Formel<br>(die Formel, die Formeln)<br><br>Die chemische Formel für Wasser ist H20."; tr: "formula<br><br>The chemical formula for water is H20."; known: false }
    ListElement { txt: "Forscher<br>(der Forscher, die Forscher)<br><br>Die beiden Forscher bekamen für ihre Arbeiten einen Preis."; tr: "researcher<br><br>Both researchers received a prize for their work."; known: false }
    ListElement { txt: "fortschrittlich<br>(fortschrittlich)<br><br>Die Kinder an dieser Schule werden sehr fortschrittlich erzogen."; tr: "progressive<br><br>The children at this school are given a progressive education."; known: false }
    ListElement { txt: "Geographie<br>(die Geographie, kein Plural)<br><br>Geographie ist ein interessantes Fach."; tr: "geography (as academic subject)<br><br>Geography is an interesting subject."; known: false }
    ListElement { txt: "historisch<br>(historisch)<br><br>Bei den Bauarbeiten wurden historische Gräber entdeckt."; tr: "historical<br><br>During construction a number of historical graves were discovered."; known: false }
    ListElement { txt: "konkret<br>(konkret)<br><br>Sie hat noch keine konkreten Vorschläge gemacht."; tr: "concrete<br><br>She has yet to make any concrete suggestions."; known: false }
    ListElement { txt: "Konzentration<br>(die Konzentration, kein Plural)<br><br>Der Text ist schwierig. Das Lesen erfordert hohe Konzentration."; tr: "concentration<br><br>The text is difficult. Reading it requires considerable concentration."; known: false }
    ListElement { txt: "konzentrieren<br>(konzentrieren, konzentrierte, hat konzentriert)<br><br>Stör mich nicht! Ich muss mich konzentrieren."; tr: "concentrate<br><br>Don't disturb me! I have to concentrate."; known: false }
    ListElement { txt: "Notiz<br>(die Notiz, die Notizen)<br><br>Ich habe mir während des Gesprächs einige Notizen gemacht."; tr: "note (written)<br><br>I took notes during the conversation,"; known: false }
    ListElement { txt: "Philosophie<br>(die Philosophie, kein Plural)<br><br>Herr Dr. Kranz ist kein Arzt, er ist Doktor der Philosophie."; tr: "philosophy<br><br>Dr. Kranz is not a physician; he is a doctor of philosophy (Ph. D)."; known: false }
    ListElement { txt: "Physik<br>(die Physik, kein Plural)<br><br>Mein Bruder studiert Physik und Mathematik."; tr: "physics<br><br>My brother is studying physics and mathematics."; known: false }
    ListElement { txt: "Praxis<br>(die Praxis, kein Plural)<br><br>Sie hat in ihrem Beruf noch wenig Praxis."; tr: "practice, experience<br><br>She doesn't yet have a lot of experience in her profession."; known: false }
    ListElement { txt: "Symbol<br>(das Symbol, die Symbole)<br><br>Das x ist das Symbol für Multiplikation in der Mathematik."; tr: "symbol<br><br>&quot;x&quot; is the symbol for multiplication in mathematics."; known: false }
    ListElement { txt: "Tabelle<br>(die Tabelle, die Tabelleen)<br><br>Die genauen Daten finden Sie in der Tabelle."; tr: "table (of information), chart<br><br>You can find the exact data in the table."; known: false }
    ListElement { txt: "These<br>(die These, die Thesen)<br><br>Die Thesen von Prof. Fuchs wurden ausführlich diskutiert."; tr: "thesis, (philosophical) concept, hypothesis<br><br>The concepts of Prof. Fuchs were thoroughly discussed."; known: false }
    ListElement { txt: "Überblick<br>(der Überblick, kein Plural)<br><br>Das Buch beginnt mit einem allgemeinen Überblick über die Geschichte des 19. Jahrhunderts."; tr: "overview<br><br>The book begins with a general overview of the history of the nineteenth century."; known: false }
    ListElement { txt: "übersetzen<br>(übersetzen, übersetzte, hat übersetzt)<br><br>Ich kann leider kein Englisch. Könnten Sie mir den Brief übersetzen?"; tr: "translate<br><br>I do not know English. Could you translate the letter for me?"; known: false }
    ListElement { txt: "Übersetzung<br>(die Übersetzung, die Übersetzungen)<br><br>Für das Buch gibt es leider noch keine deutsche Übersetzung."; tr: "translation<br><br>Unfortunately, there is not yet a German translation for the book."; known: false }
    ListElement { txt: "unbekannt<br>(unbekannt)<br><br>Sein Vorname ist Horst, sein Nachname ist mir unbekannt."; tr: "unknown<br><br>His first name is Horst; I do not know his last name."; known: false }
    ListElement { txt: "untersuchen<br>(untersuchen, untersuchte, hat untersucht)<br><br>Die Ursache des Unglücks wurde nicht sorgfältig untersucht."; tr: "examine, investigate<br><br>The cause of the accident was not thoroughly investigated."; known: false }
    ListElement { txt: "Untersuchung<br>(die Untersuchung, die Untersuchungen)<br><br>Das Ergebnis der Untersuchung war negativ."; tr: "examination, test, investigation<br><br>The results of the test investigation were negative."; known: false }
    ListElement { txt: "Verfasser<br>(der Verfasser, die Verfasser)<br><br>Ich kenne nur den Titel des Buches, den Namen der Verfasserin habe ich vergessen."; tr: "author<br><br>I know only the title of the book; I've forgotten the name of the author."; known: false }
    ListElement { txt: "Verständnis<br>(das Verständnis, kein Plural)<br><br>Er zeigte viel Verständnis für meine schwierige Situation."; tr: "understanding<br><br>He showed considerable understanding for my difficult situation."; known: false }
    ListElement { txt: "vorlesen<br>(vorlesen, las vor, hat vorgelesen)<br><br>Ich lese den Kindern jeden Abend eine Geschichte vor."; tr: "read aloud, lecture<br><br>Every evening I read the children a story."; known: false }

}

