import QtQuick 2.2

ListModel {
    property string name: "03.7_Certainty_and_Doubt"
    ListElement { txt: "angeblich<br>(angeblich)<br><br>Sie ist angeblich krank."; tr: "supposed, alleged<br><br>She is supposedly ill."; known: false }
    ListElement { txt: "Annahme<br>(die Annahme, die Annahmen)<br><br>Sicher bin ich nicht, das ist nur eine Annahme."; tr: "assumption<br><br>I'm not certain; that is only an assumption."; known: false }
    ListElement { txt: "annehmen<br>(annehmen, nahm an, hat angenommen)<br><br>Ich nehme an, dass es gleich regnet."; tr: "assume<br><br>I assume it'll rain any minute."; known: false }
    ListElement { txt: "anscheinend<br>(anscheinend)<br><br>Frank meldet sich nicht am Telefon. Er ist anscheinend nicht zu Hause."; tr: "apparent<br><br>Frank isn't answering the phone. He's apparently not home."; known: false }
    ListElement { txt: "behaupten<br>(behaupten, behauptete, hat behauptet)<br><br>Er behauptet, dass er davon nichts gewusst hat."; tr: "claim<br><br>He claims he knew nothing about it."; known: false }
    ListElement { txt: "bestimmt<br>(bestimmt)<br><br>Ich werde bestimmt anrufen."; tr: "certain<br><br>I will certainly call."; known: false }
    ListElement { txt: "bestätigen<br>(bestätigen, bestätigte, hat bestätigt)<br><br>Die Zeugin hat seine Aussage bestätigt."; tr: "acknowledge, confirm<br><br>The witness confirmed his testimony."; known: false }
    ListElement { txt: "deutlich<br>(deutlich)<br><br>Man kann ihn gut verstehen. Er spricht sehr deutlich."; tr: "clear<br><br>We can understand him well. He speaks very clearly."; known: false }
    ListElement { txt: "eindeutig<br>(eindeutig)<br><br>Ihre Antwort war eindeutig  nein'."; tr: "clear, unambiguous<br><br>Her answer was clearly &quot;no&quot;."; known: false }
    ListElement { txt: "Eindruck<br>(der Eindruck, die Eindrücke)<br><br>Ich habe den Eindruck, dass dir das Essen nicht schmeckt."; tr: "impression<br><br>I have the impression that you don't like the food."; known: false }
    ListElement { txt: "entscheiden<br>(entscheiden, entschied, hat entschieden)<br><br>Ich kann selbst entscheiden, wann ich mit der Arbeit beginne. Sie kann sich nicht entscheiden, welchen Pullover sie kaufen möchte."; tr: "decide<br><br>I can decide on my own when to start work. She can't decide which sweater to buy."; known: false }
    ListElement { txt: "Entscheidung<br>(die Entscheidung, die Entscheidungen)<br><br>Die Entscheidung war richtig, den Vertrag zu kündigen."; tr: "decision<br><br>The decision to cancel the contract was right."; known: false }
    ListElement { txt: "eventuell<br>(eventuell)<br><br>Susanne bringt eventuell ihre Schwester mit."; tr: "perhaps, maybe<br><br>Maybe Susanne is bringing along her sister."; known: false }
    ListElement { txt: "Frage<br>(die Frage, die Fragen)<br><br>Er hat die Frage richtig beantwortet."; tr: "question<br><br>He answered the question correctly."; known: false }
    ListElement { txt: "fragen<br>(fragen, fragte, hat gefragt)<br><br>Er hat mich gefragt, ab ich ihn nach Hause bringen kann. Der Kunde hat nach dem Liefertermin gefragt. Ich frage mich, wie wir das schaffen sollen."; tr: "question, ask<br><br>He asked me if I could take him home. The customer asked when it would be delivered. I wonder [lit.: ask myself] how we're supposed to manage that."; known: false }
    ListElement { txt: "gelten<br>(gelten, galt, hat gegolten)<br><br>Der Pass gilt fünf Jahre. Sie gilt als zuverlässig."; tr: "be good for, count, be<br><br>The passport is good for five years. She is considered to be reliable."; known: false }
    ListElement { txt: "gewiss<br>(gewiss)<br><br>Er hat eine gewisse Ähnlichkeit mit seinem Vater. Der Tod ist jedem Menschen gewiss. Er ist gewiss noch nicht fertig, er braucht immer viel Zeit."; tr: "certain<br><br>He has a certain resemblance to his father. Death is a certain fact for everyo­e. He is certainly not finished yet; he always needs a lot of time."; known: false }
    ListElement { txt: "glauben<br>(glauben, glaubte, hat geglaubt)<br><br>Ich glaube, ihr Nachname ist Weber. Er glaubt an eine bessere Zukunft."; tr: "think, believe<br><br>I think her last name is Weber. He believes in a better future."; known: false }
    ListElement { txt: "hoffentlich<br>(hoffentlich)<br><br>Hoffentlich wird er bald gesund."; tr: "hopefully<br><br>Hopefully he will get well soon."; known: false }
    ListElement { txt: "irren<br>(irren, irrte, hat geirrt)<br><br>Sie irren sich, in Mühldorf gibt es keinen Bahnhof."; tr: "be mistaken, wrong<br><br>You are mistaken; there's no train station in Mühldorf."; known: false }
    ListElement { txt: "Irrtum<br>(der Irrtum, die Irrtümer)<br><br>Sie haben mir den falschen Zimmerschlüssel gegeben. Verzeihung, das war ein Irrtum."; tr: "error, mistake<br><br>O You gave me the wrong key. D I'm sorry that was a mistake."; known: false }
    ListElement { txt: "klappen<br>(klappen, klappte, hat geklappt)<br><br>Es gab keine Schwierigkeiten, alles hat geklappt."; tr: "work out, turn out successfully<br><br>There were no difficulties; everything worked (out)."; known: false }
    ListElement { txt: "können Mod.<br>(können Mod., konnte, hat gekonnt)<br><br>Sei nicht traurig, das Wetter kann morgen schon besser sein."; tr: "can vm<br><br>Don't be sad; the weather might/could be better tomorrow."; known: false }
    ListElement { txt: "leugnen<br>(leugnen, leugnete, hat geleugnet)<br><br>Der Angeklagte leugnete seine Schuld."; tr: "deny<br><br>The defendant denied his guilt."; known: false }
    ListElement { txt: "möglich<br>(möglich)<br><br>Es ist möglich, dass er gelogen hat. Ich möchte Frau Simon sprechen. Das ist leider nicht möglich, sie ist heute verreist."; tr: "possible<br><br>It is possible that he lied. I'd like to speak to Ms. Simon. That is unfortunately not possible; she is out of town today."; known: false }
    ListElement { txt: "möglicherweise<br>(möglicherweise)<br><br>Möglicherweise komme ich heute später nach Hause."; tr: "possibly, maybe<br><br>Maybe I will get home late today."; known: false }
    ListElement { txt: "Möglichkeit<br>(die Möglichkeit, die Möglichkeiten)<br><br>Ich sehe keine Möglichkeit, ihm zu helfen."; tr: "possibility<br><br>I see no possibility of helping him."; known: false }
    ListElement { txt: "scheinbar<br>(scheinbar)<br><br>Sie hat mich gegrüßt. Scheinbar kennt sie mich."; tr: "apparent<br><br>She greeted me. Apparently she knows me."; known: false }
    ListElement { txt: "sicher<br>(sicher)<br><br>Ich bin sicher, dass ich die Prüfung bestehe. Sie ist immer noch nicht da, sicher hat sie den Termin vergessen."; tr: "certain, sure<br><br>I'm sure I'll pass the exam. She's still not here; she certainly forgot the appointment."; known: false }
    ListElement { txt: "Sicherheit<br>(die Sicherheit, die Sicherheiten)<br><br>Du kannst ihn so spät nicht mehr anrufen, mit Sicherheit schläft er schon."; tr: "certainty<br><br>You can't call him so late; he's surely asleep already."; known: false }
    ListElement { txt: "Tatsache<br>(die Tatsache, die Tatsachen)<br><br>Das sind Tatsachen, die man nicht leugnen kann."; tr: "fact<br><br>These are facts we cannot deny."; known: false }
    ListElement { txt: "tatsächlich<br>(tatsächlich)<br><br>Willst du bei diesem Wett er tatsächlich spazieren gehen? Ich wollte es erst nicht glauben, aber sie haben tatsächlich sieben Töchter."; tr: "real<br><br>Do you really want to go for a walk in this weather? At first I didn't believe it, but they really do have seven daughters."; known: false }
    ListElement { txt: "vermuten<br>(vermuten, vermutete, hat vermutet)<br><br>Die Polizei vermutet, dass der Mann ermordet wurde."; tr: "suppose, presume, suspect<br><br>The police suspect the man was murdered."; known: false }
    ListElement { txt: "vielleicht<br>(vielleicht)<br><br>Fragen Sie Herrn Busch. Vielleicht weiß er Bescheid."; tr: "perhaps, maybe<br><br>Ask Mr. Busch. Maybe he knows."; known: false }
    ListElement { txt: "voraussichtlich<br>(voraussichtlich)<br><br>Voraussichtlich wird es heute Nacht sehr kalt werden."; tr: "probable, likely<br><br>It is likely to get very cold tonight."; known: false }
    ListElement { txt: "wahrscheinlich<br>(wahrscheinlich)<br><br>Es geht mir nicht gut. Wahrscheinlich bekomme ich eine Erkältung."; tr: "possible, probable<br><br>I don't feel well. I'm probably getting a cold."; known: false }
    ListElement { txt: "wohl<br>(wohl)<br><br>Frau Pelz fährt ein teures Auto. Sie verdient wohl gut."; tr: "probably<br><br>Ms. Pelz has a very expensive car. I guess she earns a lot."; known: false }
    ListElement { txt: "Zweifel<br>(der Zweifel, die Zweifel)<br><br>Es besteht kein Zweifel, dass er an dem Unfall schuld war."; tr: "doubt<br><br>There's no doubt he was guilty of the accident."; known: false }
    ListElement { txt: "Ahnung<br>(die Ahnung, die Ahnungen)<br><br>Ich hatte keine Ahnung, dass Kurt verheiratet ist."; tr: "idea<br><br>I had no idea Kurt was married."; known: false }
    ListElement { txt: "ausschließen<br>(ausschließen, schloss aus, hat ausgeschlossen)<br><br>Man kann nicht ausschließen, dass er bei der Operation stirbt."; tr: "exclude<br><br>The possibility that he may die during the operation cannot be excluded."; known: false }
    ListElement { txt: "Behauptung<br>(die Behauptung, die Behauptungen)<br><br>Kannst du deine Behauptung beweisen?"; tr: "statement, assertion<br><br>Can you prove your assertion?"; known: false }
    ListElement { txt: "Beweis<br>(der Beweis, die Beweise)<br><br>Vermutlich war er der Täter, aber es gibt keine Beweise."; tr: "evidence, proof<br><br>He was probably the one who did it, but there is no proof."; known: false }
    ListElement { txt: "beweisen<br>(beweisen, bewies, hat bewiesen)<br><br>Können Sie beweisen, dass Sie am 3. August den ganzen Tag zu Hause waren?"; tr: "prove<br><br>Can you prove you were at home all day on the third of August?"; known: false }
    ListElement { txt: "bezweifeln<br>(bezweifeln, bezweifelte, hat bezweifelt)<br><br>Ich bezweifle, dass er für die Arbeit kräftig genug ist."; tr: "doubt, have doubts<br><br>I doubt that he is strong enough for this work."; known: false }
    ListElement { txt: "entschließen<br>(entschließen, entschloss, hat entschlossen)<br><br>Ich habe mich entschlossen, mit dem Rauchen aufzuhören."; tr: "decide<br><br>I have decided to stop smoking."; known: false }
    ListElement { txt: "erraten<br>(erraten, erriet, hat erraten)<br><br>Er hat die Lösung des Tests nicht gewusst, aber erraten."; tr: "guess<br><br>He didn't know the answer to the test question, but he guessed it."; known: false }
    ListElement { txt: "geheim<br>(geheim)<br><br>Die Papiere sind an einem geheimen Ort versteckt."; tr: "secret<br><br>The papers are hidden in a secret place."; known: false }
    ListElement { txt: "Geheimnis<br>(das Geheimnis, die Geheimnisse)<br><br>Sie hat Staatsgeheimnisse an eine Zeitung verraten."; tr: "secret<br><br>She revealed state secrets to a newspaper."; known: false }
    ListElement { txt: "klären<br>(klären, klärte, hat geklärt)<br><br>Ich glaube, diese Fragen lassen sich schnell klären."; tr: "clear up, explain<br><br>I think these questions can be cleared up quickly."; known: false }
    ListElement { txt: "offenbar<br>(offenbar)<br><br>Unter seiner alten Telefonnummer kann man ihn nicht erreichen. Er ist offenbar umgezogen."; tr: "apparent<br><br>We can't reach him at the number he gave us. Apparently he's moved."; known: false }
    ListElement { txt: "offensichtlich<br>(offensichtlich)<br><br>Rainer hat schlechte Laune, er hat sich offensichtlich über etwas geärgert."; tr: "apparent, obvious<br><br>Rainer is in a bad mood; apparently he's angry about something."; known: false }
    ListElement { txt: "raten<br>(raten, riet, hat geraten)<br><br>Zu dieser langen Reise kann ich dir nicht raten."; tr: "advise, give advice, recommend<br><br>I don't recommend that you take this long trip."; known: false }
    ListElement { txt: "sicherlich<br>(sicherlich)<br><br>Warum ruft Rüdiger nicht an? Das hat er sicherlich vergessen."; tr: "certainly, surely<br><br>Why doesn't Rüdiger call? He has certainly forgotten."; known: false }
    ListElement { txt: "so genannt<br>(so genannt)<br><br>Seine so genannte Cousine ist in Wahrheit seine Freundin."; tr: "so-called<br><br>His so-called cousin is really his girlfriend."; known: false }
    ListElement { txt: "wirklich<br>(wirklich)<br><br>Ein wirklicher Freund hätte dir in dieser Situation geholfen. Hast du wirklich geglaubt, dass sie dir alles erzählt hat?"; tr: "real, true<br><br>A real friend would have helped you in this situation. Did you really believe that she told you everything?"; known: false }
    ListElement { txt: "Wirklichkeit<br>(die Wirklichkeit, kein Plural)<br><br>Seine Freunde nennen ihn Teddy, in Wirklichkeit heißt er Theodor."; tr: "truth, reality<br><br>His friends call him Teddy, but in reality his name is Theodore."; known: false }
    ListElement { txt: "Wunder<br>(das Wunder, die Wunder)<br><br>Du bist viel zu dünn angezogen, kein Wunder, dass du frierst. Es wäre ein Wunder, wenn er pünktlich nach Hause käme."; tr: "surprise, miracle, wonder<br><br>You're much too lightly dressed; no wonder you're freezing. It would be a surprise if he came home on time."; known: false }
    ListElement { txt: "zweifellos<br>(zweifellos)<br><br>Wien ist zweifellos eine interessante Stadt."; tr: "doubtless, indubitable, certain, sure<br><br>Vienna is certainly an interesting city."; known: false }

}

