import QtQuick 2.2

ListModel {
    property string name: "16.1_Order_Division"
    ListElement { txt: "allein<br>(allein)<br><br>Die Arbeit schaffe ich allein. Ich bin allein wegen dir gekommen."; tr: "alone, solely<br><br>I'll get the work done alone. I came solely because of you."; known: false }
    ListElement { txt: "auch<br>(auch)<br><br>Möchtest du auch ein Eis?"; tr: "also, too<br><br>Would you like same ice cream too?"; known: false }
    ListElement { txt: "Beziehung<br>(die Beziehung, die Beziehungen)<br><br>Zwischen den beiden Ereignissen besteht eine Beziehung. Zu meinem Chef habe ich eine gute Beziehung."; tr: "relationship, connection<br><br>There's a connection between these two events. I have a good relationship with my boss."; known: false }
    ListElement { txt: "eigentlich<br>(eigentlich)<br><br>Ihre eigentlichen Interessen an der Sache kenne ich nicht. Eigentlich wollten wir das Haus nicht kaufen, sondern nur mieten."; tr: "real, actual, true<br><br>I don't know her real interests in this. We really didn't want to buy the house, just rent it."; known: false }
    ListElement { txt: "einzeln<br>(einzeln)<br><br>Jedes einzelne Teil der Maschine wurde geprüft."; tr: "single<br><br>Every single part of the machine was tested."; known: false }
    ListElement { txt: "fehlen<br>(fehlen, fehlte, hat gefehlt)<br><br>Es fehlen noch Steine. Diese hier reichen nicht für die ganze Mauer."; tr: "be missing<br><br>There are still stones missing. There aren't enough here for the whole wall."; known: false }
    ListElement { txt: "folgende<br>(folgende)<br><br>Überfolgende Punkte müssen wir noch sprechen."; tr: "(the) following<br><br>We still have to discuss the following points."; known: false }
    ListElement { txt: "Gegensatz<br>(der Gegensatz, die Gegensätze)<br><br>Trotz großer Gegensätze haben wir weiter verhandelt."; tr: "difference, conflict<br><br>We continued to negotiate in spite of great differences."; known: false }
    ListElement { txt: "Gegenteil<br>(das Gegenteil, die Gegenteile)<br><br>Er macht genau das Gegenteil von meinem Rat."; tr: "opposite<br><br>He's doing just the opposite of what I advised."; known: false }
    ListElement { txt: "gehören<br>(gehören, gehörte, hat gehört)<br><br>Wem gehören diese Sachen? Diese Sachen gehören in den Schrank."; tr: "belong<br><br>To whom do these things belang? These things belong in the closet."; known: false }
    ListElement { txt: "gemeinsam<br>(gemeinsam)<br><br>Lass uns gemeinsam ins Kino gehen. Sie haben ein gemeinsames Geschäft."; tr: "together<br><br>Let's go to the movie together. They have a business together."; known: false }
    ListElement { txt: "jeweils<br>(jeweils)<br><br>Die Miete muss jeweils am ersten Tag des Monats bezahlt werden."; tr: "each time<br><br>The rent has to be paid each time on the first day of the month."; known: false }
    ListElement { txt: "letzte<br>(letzte)<br><br>Ich lese gerade die letzten Seiten des Buches."; tr: "last<br><br>I'm just now reading the last pages of the book."; known: false }
    ListElement { txt: "miteinander<br>(miteinander)<br><br>Wir spielen oft Schach miteinander."; tr: "with each other<br><br>We often play chess with each other."; known: false }
    ListElement { txt: "mittlere<br>(mittlere)<br><br>Die Fotos sind im mittleren Fach."; tr: "middle<br><br>The photos are in the middle drawer."; known: false }
    ListElement { txt: "nächste<br>(nächste)<br><br>An der nächsten Station müssen wir aussteigen."; tr: "next<br><br>We have to get out at the next station."; known: false }
    ListElement { txt: "nebenbei<br>(nebenbei)<br><br>Beim Lesen kann ich nebenbei keine Musik hören."; tr: "at the same time, simultaneous<br><br>When reading I can't listen to music at the same time."; known: false }
    ListElement { txt: "nebeneinander<br>(nebeneinander)<br><br>In der Schule haben wir nebeneinander gesessen."; tr: "next to each other<br><br>In school we sat next to each other."; known: false }
    ListElement { txt: "nur<br>(nur)<br><br>Den Ort kann man nur zu Fuß erreichen."; tr: "only<br><br>You can only get to that place on foot."; known: false }
    ListElement { txt: "ordnen<br>(ordnen, ordnete, hat geordnet.)<br><br>Die Bücher sind nach Themen geordnet."; tr: "arrange<br><br>The books are arranged according to subject matter."; known: false }
    ListElement { txt: "Ordnung<br>(die Ordnung, kein Plural)<br><br>Er ist für die Ordnung im Lager verantwortlich."; tr: "order, rules<br><br>He's responsible for order in the storage."; known: false }
    ListElement { txt: "Regel<br>(die Regel, die Regeln)<br><br>Die Regel dieses Spiels kenne ich nicht."; tr: "rule<br><br>I don't know the rules of this game."; known: false }
    ListElement { txt: "Reihe<br>(die Reihe, die Reihen)<br><br>Wir haben die Plätze 24 und 25 in Reihe 12."; tr: "row<br><br>We have seats 24 and 25 in row 12."; known: false }
    ListElement { txt: "Reihenfolge<br>(die Reihenfolge, die Reihenfolgen)<br><br>In welcher Reihenfolge sollen die Arbeiten gemacht werden?"; tr: "order (of presentation)<br><br>In what order should the work be done?"; known: false }
    ListElement { txt: "sonst<br>(sonst)<br><br>Wer will sonst noch mitspielen? Du musst gehen, sonst kommst du zu spät. Ich habe lange nichts von ihm gehört. Wir haben uns sonst jede Woche getroffen."; tr: "else, otherwise<br><br>Who else wants to play? You have to leave; otherwise you'll get there too late. I haven't heard anything from him for a long time. Other than that we saw each other every week."; known: false }
    ListElement { txt: "sonstige<br>(sonstige)<br><br>In dem Geschäft kann man Geschirr und sonstige Haushaltswaren kaufen."; tr: "other<br><br>In the store you can buy dinnerware and other housewares."; known: false }
    ListElement { txt: "System<br>(das System, die Systeme)<br><br>Welches System hat dein Computer?"; tr: "system<br><br>What system does your computer use?"; known: false }
    ListElement { txt: "Unordnung<br>(die Unordnung, kein Plural)<br><br>Auf seinem Schreibtisch ist eine große Unordnung."; tr: "mess n disorder,<br><br>Things are in a big mess on his desk."; known: false }
    ListElement { txt: "unterscheiden<br>(unterscheiden, unterschied, hat unterschieden)<br><br>Die beiden Zwillinge kann ich nicht unterscheiden."; tr: "distinguish, tell the difference<br><br>I can't tell the difference between the twins."; known: false }
    ListElement { txt: "Unterschied<br>(der Unterschied, die Unterschiede)<br><br>Bei den Geräten gibt es große Preis und Qualitätsunterschiede."; tr: "difference<br><br>There are great quality and price differences among the tools."; known: false }
    ListElement { txt: "Verhältnis<br>(das Verhältnis, die Verhältnisse)<br><br>Das Pulver muss mit Wasser im Verhältnis 3:1 gemischt werden."; tr: "proportion<br><br>The powder must be mixed with water in a proportion of 3 to 1."; known: false }
    ListElement { txt: "voneinander<br>(voneinander)<br><br>Wir haben voneinander viel gelernt."; tr: "from each other<br><br>We learned a lot from each other."; known: false }
    ListElement { txt: "zusammen<br>(zusammen)<br><br>Wir arbeiten seit acht Jahren zusammen."; tr: "together<br><br>We've been working together for eight years."; known: false }
    ListElement { txt: "Abschnitt<br>(der Abschnitt, die Abschnitte)<br><br>Hast du jeden Abschnitt des Textes genau gelesen?"; tr: "part, section<br><br>Have you read every part of the text carefully?"; known: false }
    ListElement { txt: "Anteil<br>(der Anteil, die Anteile)<br><br>Der größte Anteil an dem Unternehmen gehört einer Bank."; tr: "share, interest<br><br>A bank owns the greatest share of the business."; known: false }
    ListElement { txt: "auslassen<br>(auslassen, ließ aus, hat ausgelassen)<br><br>In der Zeile ist ein Wort ausgelassen worden."; tr: "leave out<br><br>A word was left out in that line."; known: false }
    ListElement { txt: "Ausnahme<br>(die Ausnahme, die Ausnahmen)<br><br>Sie können heute früher gehen, aber das ist eine Ausnahme."; tr: "exception<br><br>You can leave early today, but that's an exception."; known: false }
    ListElement { txt: "ausschließlich<br>(ausschließlich)<br><br>Sie trinkt abends ausschließlich schwarzen Tee."; tr: "only, without exception, exclusively<br><br>In the evening she drinks only tea."; known: false }
    ListElement { txt: "beispielsweise<br>(beispielsweise)<br><br>Alle Kopien sind schlecht, schauen Sie sich beispielsweise diese hier an."; tr: "for, as an example<br><br>All the copies are bad; look at this one as an example."; known: false }
    ListElement { txt: "Bestandteil<br>(der Bestandteil, die Bestandteile)<br><br>Es gibt heute Farben ohne giftige Bestandteile."; tr: "part, component, ingredient<br><br>Today there are paints without poisonous components."; known: false }
    ListElement { txt: "betreffen<br>(betreffen, betraf, hat betroffen)<br><br>Ich bin von der neuen Regelung nicht betroffen."; tr: "be related, concerned by, affect<br><br>I'm not affected by the new rule."; known: false }
    ListElement { txt: "derartig<br>(derartig)<br><br>Eine derartige Krankheit gibt es selten."; tr: "such, like that<br><br>A disease like that is rare."; known: false }
    ListElement { txt: "Detail<br>(das Detail, die Details)<br><br>Über einige Details des Vertrages müssen wir noch sprechen."; tr: "detail<br><br>We still have to discuss some details of the contract."; known: false }
    ListElement { txt: "direkt<br>(direkt)<br><br>Das ist der direkteste Weg. Direkt neben der Post ist ein Supermarkt."; tr: "direct, right<br><br>That is the most direct way. There's a supermarket right next to the post office."; known: false }
    ListElement { txt: "einheitlich<br>(einheitlich)<br><br>Die Regelung ist in allen Firmen einheitlich."; tr: "the same, uniform<br><br>The regulation is the same in all firms."; known: false }
    ListElement { txt: "Einzelheit<br>(die Einzelheit, die Einzelheiten)<br><br>Die genauen Einzelheiten des Plans kenne ich nicht."; tr: "detail<br><br>I don't know the exact details of the plan."; known: false }
    ListElement { txt: "Element<br>(das Element, die Elemente)<br><br>Die Elemente des Systems passen alle zusammen."; tr: "element, part<br><br>All the elements of the system fit together."; known: false }
    ListElement { txt: "entgegengesetzt<br>(entgegengesetzt)<br><br>Es wurden zwei entgegengesetzte Vorschläge gemacht."; tr: "opposing, opposite<br><br>Two opposing suggestions were made."; known: false }
    ListElement { txt: "erforderlich<br>(erforderlich)<br><br>Für diese Arbeit ist viel Erfahrung erforderlich."; tr: "required, necessary<br><br>For this work, much experience is required."; known: false }
    ListElement { txt: "erfordern<br>(erfordern, erforderte, hat erfordert)<br><br>Dieser Beruf erfordert Fremdsprachenkenntnisse."; tr: "require<br><br>This profession requires the knowledge of foreign languages."; known: false }
    ListElement { txt: "Ersatz<br>(der Ersatz, kein Plural)<br><br>Für den kranken Mitarbeiter wurde noch kein Ersatz gefunden."; tr: "substitute, replacement<br><br>There was still no substitute for the sick worker."; known: false }
    ListElement { txt: "folgen<br>(folgen, folgte, ist(hat) gefolgt)<br><br>Wann folgt der 2. Teil des Berichts? Ich zeige Ihnen den Weg. Bitte folgen Sie mir!"; tr: "follow, continue<br><br>When will the second part of the report be out? I'll show you the way. Please follow me."; known: false }
    ListElement { txt: "Gebiet<br>(das Gebiet, die Gebiete)<br><br>Er ist Fachmann auf seinem Gebiet. Große Gebiete des Landes sind Wüste."; tr: "field, area<br><br>He is an expert in his field. Large areas of the country are desert."; known: false }
    ListElement { txt: "gegenseitig<br>(gegenseitig)<br><br>Deutschland und die USA haben ein gegenseitiges Abkommen geschlossen."; tr: "mutual, bilateral<br><br>Germany and the USA made a bilateral arrangement."; known: false }
    ListElement { txt: "Hauptsache<br>(die Hauptsache, die Hauptsachen)<br><br>Gute Qualität des Materials ist die Hauptsache."; tr: "main thing, most important thing<br><br>The quality of the materials is the most important thing."; known: false }
    ListElement { txt: "hierbei<br>(hierbei)<br><br>Hierbei kann ich dir nicht helfen."; tr: "with this, at this time<br><br>I can't help you with this."; known: false }
    ListElement { txt: "hierfür<br>(hierfür)<br><br>Hierfür brauchst du Spezialwerkzeug."; tr: "for this<br><br>You need special tools for this."; known: false }
    ListElement { txt: "Hinsicht<br>(die Hinsicht, die Hinsichten)<br><br>In dieser Hinsicht muss ich Ihnen Recht geben."; tr: "regard, respect<br><br>In regards to this, I must say you're right."; known: false }
    ListElement { txt: "Klasse<br>(die Klasse, die Klassen)<br><br>Sie ist erster Klasse gereist. Das ist das beste Auto in dieser Preisklasse."; tr: "class<br><br>She traveled in first class. That is the best car in that price class."; known: false }
    ListElement { txt: "Kombination<br>(die Kombination, die Kombinationen)<br><br>Die Sendung war eine gelungene Kombination von Information und Unterhaltung."; tr: "combination<br><br>The broadcast was a successful combination of news and entertainment."; known: false }
    ListElement { txt: "Liste<br>(die Liste, die Listen)<br><br>Ihren Namen kann ich in der Liste nicht finden."; tr: "list<br><br>I can't find your name in the list."; known: false }
    ListElement { txt: "Niveau<br>(das Niveau, die Niveaus)<br><br>Die Ausstellung hatte hohes Niveau."; tr: "level, class<br><br>The exhibition was high class."; known: false }
    ListElement { txt: "Original<br>(das Original, die Originale)<br><br>Wo ist das Original des Briefes? Ich habe nur eine Kopie."; tr: "original<br><br>Where is the original of the letter? I only have a copy."; known: false }
    ListElement { txt: "Schwerpunkt<br>(der Schwerpunkt, die Schwerpunkte)<br><br>Kürzere Arbeitszeiten sind der Schwerpunkt der Forderungen."; tr: "most important point, main focus<br><br>Shorter working hours are the most important point of the demands."; known: false }
    ListElement { txt: "Serie<br>(die Serie, die Serien)<br><br>Das ist der fünfte Band einer Serie von Abenteuerromanen."; tr: "series<br><br>That is the fifth volume of a series of adventure novels."; known: false }
    ListElement { txt: "Typ<br>(der Typ, die Typen)<br><br>Die Maschinen des neuen Typs sind schneller und leiser."; tr: "type<br><br>The new type machines are faster and quieter."; known: false }
    ListElement { txt: "überflüssig<br>(überflüssig)<br><br>Mach dir keine überflüssigen Sorgen! Wir werden die Arbeit schon schaffen."; tr: "unnecessary, superfluous<br><br>Don't worry unnecessarily. We'll get the work done."; known: false }
    ListElement { txt: "umgekehrt<br>(umgekehrt)<br><br>Sie hat es umgekehrt gemacht, nicht wie ich es ihr geraten habe."; tr: "the opposite, the other way around, vice versa<br><br>She did it the other way around, not the way I advised her."; known: false }
    ListElement { txt: "untereinander<br>(untereinander)<br><br>Stell die Kisten untereinander. Wir haben selten Streit untereinander."; tr: "on top of each other, with each other<br><br>Put the boxes on top of each other. We seldom have arguments with each other."; known: false }
    ListElement { txt: "ursprünglich<br>(ursprünglich)<br><br>Ursprünglich war die Reise anders geplant."; tr: "original, initial<br><br>Originally the trip was planned in a different way."; known: false }
    ListElement { txt: "verschiedenartig<br>(verschiedenartig)<br><br>Trotz verschiedenartiger Meinungen verstehen wir uns gut."; tr: "different<br><br>We understand each other well in spite of differing opinions."; known: false }
    ListElement { txt: "weiter<br>(weiter)<br><br>Gibt es noch weitere Probleme als diese? Wir sollen morgen Bescheid bekommen, man hat mir weiter nichts gesagt."; tr: "more, additional, further<br><br>Are there still more problems besides these? We should find out tomorrow; no one has told me anything additional."; known: false }

}

