import QtQuick 2.2

ListModel {
    property string name: "02.3_Doing"
    ListElement { txt: "Absicht<br>(die Absicht, die Absichten)<br><br>Ich hatte nicht die Absicht, dich zu beleidigen."; tr: "intention<br><br>I did not intend to insult you."; known: false }
    ListElement { txt: "absichtlich<br>(absichtlich)<br><br>Er macht das absichtlich, um mich zu ärgern."; tr: "intentional, deliberate<br><br>He does that deliberately, just to make me angry."; known: false }
    ListElement { txt: "Arbeit<br>(die Arbeit, die Arbeiten)<br><br>Die Arbeit ist ziemlich langweilig. Sie wurde vor fünf Monaten entlassen und hat immer noch keine neue Arbeit gefunden."; tr: "work, job<br><br>The work is rather boring. She was laid off five months ago and has not yet found a new job."; known: false }
    ListElement { txt: "arbeiten<br>(arbeiten, arbeitete, hat gearbeitet)<br><br>Er arbeitet sehr sorgfältig."; tr: "work<br><br>He works very carefully."; known: false }
    ListElement { txt: "bemühen<br>(bemühen, bemühte, hat bemüht)<br><br>Wir werden uns bemühen, die Arbeit bis Freitag fertig zu machen."; tr: "work (hard), try (hard), do one's best<br><br>We will do our best to finish the work by Friday."; known: false }
    ListElement { txt: "beschließen<br>(beschließen, beschloss, hat beschlossen)<br><br>Sie hat beschlossen, mit dem Rauchen aufzuhören."; tr: "decide<br><br>She decided to give up smoking."; known: false }
    ListElement { txt: "beschäftigen<br>(beschäftigen, + Präp. (mit) beschäftigte, hat beschäftigt)<br><br>Die Firma beschäftigt 200 Mitarbeiter. Dieses Thema beschäftigt ihn schon lange. Sie beschäftigt sich seit Jahren mit deutscher Literatur."; tr: "occupy, employ, deal with, work with<br><br>The company employs 200 people. This topic has been occupying him (his time) for a long time. She has been dealing with German literature for years."; known: false }
    ListElement { txt: "Beschäftigung<br>(die Beschäftigung, die Beschäftigungen)<br><br>Er kann nicht ohne Arbeit sein. Er sucht immer eine Beschäftigung."; tr: "work, employment<br><br>He cannot live without work. He is constantly looking for something to do."; known: false }
    ListElement { txt: "besorgen<br>(besorgen, besorgte, hat besorgt)<br><br>Ich fahre einkaufen. Soll ich für dich etwas besorgen?"; tr: "get, pick up<br><br>I'm going shopping. Do you want me to pick up anything for you?"; known: false }
    ListElement { txt: "beteiligen<br>(beteiligen, beteiligte, hat beteiligt)<br><br>Möchtest du dich an dem Spiel beteiligen?"; tr: "take part in, participate in<br><br>Would you like to join the game?"; known: false }
    ListElement { txt: "gelingen<br>(gelingen, gelang, ist gelungen)<br><br>Es ist mir nicht gelungen, den Fehler zu finden."; tr: "succeed<br><br>I did not succeed in finding the mistake."; known: false }
    ListElement { txt: "gewöhnen<br>(gewöhnen, gewöhnte, hat gewöhnt)<br><br>An meine neue Brille habe ich mich schnell gewöhnt."; tr: "get used to<br><br>I got used to my new glasses very fast."; known: false }
    ListElement { txt: "Handlung<br>(die Handlung, die Handlungen)<br><br>War Ihnen nicht klar, welche Folgen Ihre Handlung haben könnte?"; tr: "action, plot (of a story, play)<br><br>Wasn't it clear to you what consequences your actions would have?"; known: false }
    ListElement { txt: "können<br>(können, konnte, hat gekonnt)<br><br>Er kann einfach alles. Wenn Sie Zeit haben, können Sie mich morgen besuchen. Kann ich Ihnen einen Kaffee anbieten?"; tr: "be able to, be capable<br><br>He can do simply everything. If you have time, can you come see me tomorrow? Can I offer you a cup of coffee?"; known: false }
    ListElement { txt: "machen<br>(machen, machte, hat gemacht)<br><br>Wer macht heute das Abendessen? Diese Arbeit kann ich selbst machen. Mit dem Geschenk hast du mir eine große Freude gemacht. Den Schrank habe ich machen lassen. Wissen Sie, wie das gemacht wird? Mach schnell! Das macht 12,40 DM."; tr: "do, make<br><br>Who's going to make dinner today? I can do this work myself. Your gift has made me very happy. I had this cabinet made. Do you know how that is done? Hurry up! That makes 12 Marks 40."; known: false }
    ListElement { txt: "Mühe<br>(die Mühe, die Mühen)<br><br>Gib dir Mühe, dann klappt es auch."; tr: "effort, hard work<br><br>Make an effort, and everything will go well."; known: false }
    ListElement { txt: "Plan<br>(der Plan, die Pläne)<br><br>Der neue Finanzplan muss vom Chef noch genehmigt werden. Hast du einen Plan des Grundstücks?"; tr: "plan<br><br>The new finance plan still has to be approved by the boss. Do you have a plan of the lot?"; known: false }
    ListElement { txt: "planen<br>(planen, plante, hat geplant)<br><br>Die Arbeit ist gut geplant worden."; tr: "plan<br><br>The work was planned well."; known: false }
    ListElement { txt: "probieren<br>(probieren, probierte, hat probiert)<br><br>Probier du mall Ich kann die Tür nicht öffnen."; tr: "try (out)<br><br>You try it! l can't open the door."; known: false }
    ListElement { txt: "Tätigkeit<br>(die Tätigkeit, die Tätigkeiten)<br><br>Für mich ist Putzen die unangenehmste Tätigkeit."; tr: "activity<br><br>For me cleaning the house is the most unpleasant of activities."; known: false }
    ListElement { txt: "teilnehmen<br>(teilnehmen, nahm teil, hat teilgenommen)<br><br>Diesen Winter nehme ich wieder an einem Skikurs teil."; tr: "participate in, take part in<br><br>This winter I'm going to take part in a ski course again."; known: false }
    ListElement { txt: "tun<br>(tun, tat, hat getan)<br><br>Im Geschäft war viel zu tun. Was tust du in deiner Freizeit? Ich habe mir weh getan. Er ist gar nicht müde. Er tut nur so."; tr: "do, pretend, act<br><br>In the office there was much to do. What do you do in your leisure time? I hurt myself. He is not tired at all. He is just pretending."; known: false }
    ListElement { txt: "üben<br>(üben, übte, hat geübt)<br><br>Sie muss noch ein bisschen üben. Dann kann sie bald gut schwimmen."; tr: "exercise, practice<br><br>She has to exercise a bit. Then she will be able to swim well soon."; known: false }
    ListElement { txt: "vermeiden<br>(vermeiden, vermied, hat vermieden)<br><br>Der Unfall hätte vermieden werden können."; tr: "avoid<br><br>The accident could have been avoided."; known: false }
    ListElement { txt: "versuchen<br>(versuchen, versuchte, hat versucht)<br><br>Ich habe es versucht, aber ich kann die Kiste nicht alleine tragen."; tr: "try, attempt<br><br>I tried, but I cannot carry the box alone."; known: false }
    ListElement { txt: "verwechseln<br>(verwechseln, verwechselte, hat verwechselt)<br><br>Du hast die beiden Flaschen verwechselt."; tr: "mix up, confuse<br><br>You mixed up the two bottles."; known: false }
    ListElement { txt: "vorhaben<br>(vorhaben, hatte vor, hat vorgehabt)<br><br>Was habt ihr am Wochenende vor?"; tr: "intend, plan<br><br>What are you planning to do on the weekend?"; known: false }
    ListElement { txt: "Werk<br>(das Werk, die Werke)<br><br>Die bekanntesten Werke der Malerin sind in diesem Museum zu sehen."; tr: "work<br><br>The best known works of the artist can be seen in this museum."; known: false }
    ListElement { txt: "winken<br>(winken, winkte, hat gewunken)<br><br>Er winkte, als der Zug abfuhr."; tr: "wave (good-bye)<br><br>He waved as the train departed."; known: false }
    ListElement { txt: "aktiv<br>(aktiv)<br><br>Trotz ihres hohen Alters ist sie noch sehr aktiv."; tr: "active<br><br>In spite of her advanced age she is still very active. ?"; known: false }
    ListElement { txt: "Aktivität<br>(die Aktivität, die Aktivitäten)<br><br>Wenn Sie Karriere machen wollen, müssen Sie mehr. Aktivität zeigen."; tr: "activity<br><br>If you want to move up the career ladder, you have to show more activity."; known: false }
    ListElement { txt: "Angewohnheit<br>(die Angewohnheit, die Angewohnheiten)<br><br>Sie hat die Angewohnheit, während des Essens zu lesen."; tr: "habit<br><br>She has the habit of reading while she eats."; known: false }
    ListElement { txt: "anstrengen<br>(anstrengen, strengte an, hat angestrengt)<br><br>Der Nachtdienst strengt ihn sehr an. Du musst dich mehr anstrengen, sonst schaffst du es nicht."; tr: "exert, stress, exhaust, make an effort<br><br>The night shift really exhausts him. You have to make more of an effort; otherwise you won't succeed."; known: false }
    ListElement { txt: "Anstrengung<br>(die Anstrengung, die Anstrengungen)<br><br>Die Anstrengung hat sich gelohnt."; tr: "effort, exertion, exhaustion<br><br>The effort was worth it."; known: false }
    ListElement { txt: "aushalten<br>(aushalten, hielt aus, hat ausgehalten)<br><br>Was für eine Hitze heute! Das kann man ja kaum aushalten,"; tr: "(with)stand<br><br>It is really hot today! You can hardly stand it!"; known: false }
    ListElement { txt: "beabsichtigen<br>(beabsichtigen, beabsichtigte, hat beabsichtigt)<br><br>Klaus und Bernd beabsichtigen, gemeinsam eine Wohnung zu mieten."; tr: "intend<br><br>Klaus and Bernd intend to rent an apartment (BE: flat) together."; known: false }
    ListElement { txt: "beachten<br>(beachten, beachtete, hat beachtet)<br><br>Sein Befehl wurde nicht beachtet."; tr: "pay attention (to), regard, obey, respect<br><br>His order was not respected."; known: false }
    ListElement { txt: "befassen<br>(befassen, befasste, hat befasst)<br><br>Mit diesem Thema befasse ich mich schon seit Jahren."; tr: "deal with<br><br>I have been dealing with this topic for years."; known: false }
    ListElement { txt: "Bemühung<br>(die Bemühung, die Bemühungen)<br><br>Vielen Dank für Ihre Bemühungen!"; tr: "effort<br><br>Many thanks for your efforts!"; known: false }
    ListElement { txt: "Durchführung<br>(die Durchführung, kein Plural)<br><br>Die Durchführung des Plans war schwieriger als alle gedacht hatten."; tr: "carrying out, execution<br><br>The execution of the plan was more difficult than expected."; known: false }
    ListElement { txt: "durchsetzen<br>(durchsetzen, setzte durch, hat durchgesetzt)<br><br>Ich habe meinen Vorschlag durchsetzen können."; tr: "push through, enforce, assert<br><br>I was able to push through my suggestion."; known: false }
    ListElement { txt: "mühsam<br>(mühsam)<br><br>Die Arbeit war mühsam, aber sie hat sich gelohnt."; tr: "arduous<br><br>The work was arduous, but it was worth it."; known: false }
    ListElement { txt: "organisieren<br>(organisieren, organisierte, hat organisiert)<br><br>Die Feier war gut organisiert worden."; tr: "organize<br><br>The celebration was well organized."; known: false }
    ListElement { txt: "Planung<br>(die Planung, die Planungen)<br><br>Der Bau ist noch in der Planung. Die Arbeiten beginnen erst nächstes Jahr."; tr: "planning<br><br>The building is still in the planning stages. Construction won't begin until next year."; known: false }
    ListElement { txt: "realisieren<br>(realisieren, realisierte, hat realisiert)<br><br>Dieser Plan lässt sich nicht realisieren."; tr: "realize, carry out<br><br>This plan cannot be realized."; known: false }
    ListElement { txt: "schaffen<br>(schaffen, schaffte, hat geschafft)<br><br>Es tut mir leid, aber wir haben den Termin nicht mehr geschafft."; tr: "do, make, accomplish<br><br>I'm sorry, but we didn't make the appointment/deadline."; known: false }
    ListElement { txt: "Teilnehmer<br>(der Teilnehmer, die Teilnehmer)<br><br>Der Kurs hat 18 Teilnehmer."; tr: "participant<br><br>The course has 18 participants."; known: false }
    ListElement { txt: "Überwindung<br>(die Überwindung, kein Plural)<br><br>Es kostet mich große Überwindung, zu ihm freundlich zu sein."; tr: "overcoming, surmounting<br><br>It's very difficult for me to be friendly to him."; known: false }
    ListElement { txt: "unternehmen<br>(unternehmen, unternahm, hat unternommen)<br><br>Was wollen wir morgen unternehmen?"; tr: "undertake,<br><br>What do we want to do tomorrow?"; known: false }
    ListElement { txt: "Versuch<br>(der Versuch, die Versuche)<br><br>Lass uns noch einen Versuch machen. Vielleicht schaffen wir es doch allein."; tr: "attempt, try<br><br>Let's make another attempt. Maybe we can do it alone."; known: false }
    ListElement { txt: "vornehmen<br>(vornehmen, nahm vor, hat vorgenommen)<br><br>Sie hat sich vorgenommen, in Zukunft langsamer zu fahren."; tr: "intend, plan, be determined, resolve to do<br><br>She resolved to drive slower in the future."; known: false }

}

