import QtQuick 2.2

ListModel {
    property string name: "03.5_Expressing_Opinions"
    ListElement { txt: "allerdings<br>(allerdings)<br><br>Ich komme morgen vorbei, allerdings habe ich wenig Zeit."; tr: "however<br><br>I'll stop by tomorrow; however, I won't have much time."; known: false }
    ListElement { txt: "andererseits<br>(andererseits)<br><br>Einerseits ist die Wohnung sehr schön, andererseits finde ich sie sehr laut."; tr: "on the other hand<br><br>On the one hand the apartment/flat is very attractive; on the other hand, I find it very noisy."; known: false }
    ListElement { txt: "Ansicht<br>(die Ansicht, die Ansichten)<br><br>Ich kann ihn nicht leiden, er hat komische Ansichten."; tr: "opinion, idea<br><br>I don't like him; he has strange ideas."; known: false }
    ListElement { txt: "begründen<br>(begründen, begründete, hat begründet)<br><br>Der Minister hat seinen Rücktritt mit Krankheit begründet."; tr: "justify<br><br>The Secretary justified his resignation on account of illness."; known: false }
    ListElement { txt: "Begründung<br>(die Begründung, die Begründungen)<br><br>Für ihre Verspätung gab sie keine Begründung."; tr: "justification, reason<br><br>She gave no justification for arriving late."; known: false }
    ListElement { txt: "beurteilen<br>(beurteilen, beurteilte, hat beurteilt)<br><br>Den Wert dieses Bildes kann nur ein Fachmann beurteilen."; tr: "judge, determine<br><br>Only an expert can judge the value of this picture."; known: false }
    ListElement { txt: "Diskussion<br>(die Diskussion, die Diskussionen)<br><br>Über die neuen Steuergesetze gab es lange Diskussionen."; tr: "discussion<br><br>There were long discussions about the new tax laws."; known: false }
    ListElement { txt: "einerseits<br>(einerseits)<br><br>Einerseits sind die Nachbarn sehr nett, andererseits möchte ich lieber ganz einsam wohnen."; tr: "on the one hand<br><br>On the one hand my neighbors are very nice; on the other hand, I would prefer to live all by myself."; known: false }
    ListElement { txt: "empfehlen<br>(empfehlen, empfahl, hat empfohlen)<br><br>Können Sie mir einen guten Arzt empfehlen?"; tr: "recommend<br><br>Can you recommend a good doctor?"; known: false }
    ListElement { txt: "feststellen<br>(feststellen, stellte fest, hat festgestellt)<br><br>Erst als es regnete, stellte ich fest, dass ich meinen Schirm vergessen hatte. Ich möchte feststellen, dass ich von Anfang an gegen den Plan war."; tr: "determine, learn, state, realize<br><br>Only after it was raining did I realize that I had forgotten my urnbrella. I would like to state that I was against the plan from the beginning."; known: false }
    ListElement { txt: "meinen<br>(meinen, meinte, hat gemeint)<br><br>Nicht das linke, sondern das rechte Auto meine ich. Ich meine, dass unsere Regierung endlich zurücktreten sollte."; tr: "have an opinion, mean, believe<br><br>I do not mean the car on the left, but the one on the right. I believe that our government should finally resign."; known: false }
    ListElement { txt: "Meinung<br>(die Meinung, die Meinungen)<br><br>In dieser Sache habe ich eine andere Meinung als du."; tr: "opinion<br><br>My opinion on this matter is different from yours."; known: false }
    ListElement { txt: "Standpunkt<br>(der Standpunkt, die Standpunkte)<br><br>Ich stehe auf dem Standpunkt, dass Neuwahlen die beste Lösung für die Regierungskrise sind."; tr: "view, opinion, stand<br><br>I hold the view that new elections are the best solution to the government crisis."; known: false }
    ListElement { txt: "überreden<br>(überreden, überredete, hat überredet)<br><br>Wir haben sie überredet, am Wochenende mitzufahren."; tr: "persuade<br><br>We persuaded her to come along for the weekend."; known: false }
    ListElement { txt: "überzeugen<br>(überzeugen, überzeugte, hat überzeugt)<br><br>Ihre Argumente haben mich nicht überzeugt. Ich habe mich überzeugt, dass Vera die Wahrheit sagt."; tr: "convince<br><br>Your arguments have not convinced me. I confirmed that Vera is telling the truth."; known: false }
    ListElement { txt: "wesentlich<br>(wesentlich)<br><br>Das neue Programm der Regierung führte zu keiner wesentlichen Verbesserung der wirtschaftlichen Lage."; tr: "essential<br><br>The new government program led to no essential improvement in the economic situation."; known: false }
    ListElement { txt: "Argument<br>(das Argument, die Argumente)<br><br>Es gibt viele Argumente gegen die neuen Sozialgesetze."; tr: "argument<br><br>There are many arguments against the new social laws."; known: false }
    ListElement { txt: "Auffassung<br>(die Auffassung, die Auffassungen)<br><br>Sogar in der Regierung gibt es verschiedene Auffassungen über das neue Programm."; tr: "opinion<br><br>Even in the government there are different opinions about the new program."; known: false }
    ListElement { txt: "bezeichnen<br>(bezeichnen, bezeichnete, hat bezeichnet)<br><br>Die Regierungspolitik kann man als unsozial bezeichnen."; tr: "characterize, call, designate, label<br><br>The government's policies can be characterized as unsocial."; known: false }
    ListElement { txt: "diskutieren<br>(diskutieren, diskutierte, hat diskutiert)<br><br>Wir haben Ihren Vorschlag ausführlich diskutiert."; tr: "discuss<br><br>We discussed your suggestion thoroughly."; known: false }
    ListElement { txt: "Einstellung<br>(die Einstellung, die Einstellungen)<br><br>Ihre politische Einstellung kenne ich nicht."; tr: "attitude, position<br><br>I do not know her political position,"; known: false }
    ListElement { txt: "gewissermaßen<br>(gewissermaßen)<br><br>Er ist gewissermaßen der heimliche Chef der Partei."; tr: "to a certain extent, so to speak<br><br>It could be said that he is the secret leader of the party."; known: false }
    ListElement { txt: "ohnehin<br>(ohnehin)<br><br>Wir können uns in Hamburg treffen, ich bin nächste Woche ohnehin dort."; tr: "anyway, in any event<br><br>We can meet in Hamburg since I'll be there next week anyway."; known: false }
    ListElement { txt: "sachlich<br>(sachlich)<br><br>Die Diskussion war sehr sachlich."; tr: "factual, objective<br><br>The discussion was very objective."; known: false }
    ListElement { txt: "selbstverständlich<br>(selbstverständlich)<br><br>Selbstverständlich fahre ich dich nach Hause. Das ist doch klar."; tr: "of course, naturally<br><br>Of course I'll drive you home. You don't have to ask!"; known: false }
    ListElement { txt: "sowieso<br>(sowieso)<br><br>Ich nehme deinen Brief mit. Ich muss sowieso zur Post."; tr: "anyway<br><br>I'll take your letter. I'm going to the post office anyway."; known: false }
    ListElement { txt: "sozusagen<br>(sozusagen)<br><br>Sie ist sozusagen die Mutter unseres Vereins, sie kümmert sich um alles."; tr: "so to speak<br><br>She is the mother of our club, so to speak; she takes care of everything."; known: false }
    ListElement { txt: "Stellungnahme<br>(die Stellungnahme, die Stellungnahmeen)<br><br>Zu den Vorwürfen der Opposition gibt es immer noch keine Stellungnahme der Regierung."; tr: "comment, statement, response<br><br>The government still has not given a response to the opposition's accusations."; known: false }
    ListElement { txt: "Überzeugung<br>(die Überzeugung, die Überzeugungen)<br><br>.Ich bin der festen Überzeugung, dass wir auf dem richtigen Weg sind&quot;, sagte der Regierungschef."; tr: "conviction, firm opinion<br><br>&quot;I am of the firm opinion that we are on the right path,&quot; said the prime minister."; known: false }
    ListElement { txt: "unerwartet<br>(unerwartet)<br><br>Der Rücktritt des Ministers kam unerwartet."; tr: "unexpected<br><br>The resignation of the Secretary came unexpectedly."; known: false }
    ListElement { txt: "ungewöhnlich<br>(ungewöhnlich)<br><br>Die Lösung des Problems ist ungewöhnlich, aber erfolgreich."; tr: "unusual<br><br>The solution to the problem is unusual but successful."; known: false }
    ListElement { txt: "Urteil<br>(das Urteil, die Urteile)<br><br>Das Urteil in der Presse über die neuen Steuergesetze war sehr negativ."; tr: "opinion, judgment, estimation<br><br>Press reviews of the new tax laws were very negative."; known: false }
    ListElement { txt: "verurteilen<br>(verurteilen, verurteilte, hat verurteilt)<br><br>Alle Parteien im Parlament haben die politischen Morde verurteilt."; tr: "condemn<br><br>All parties condemned the assassinations."; known: false }

}

