import QtQuick 2.2

ListModel {
    property string name: "06.1_Gen._Busn._and_Admin."
    ListElement { txt: "Angebot<br>(das Angebot, die Angebote)<br><br>Das Angebot der Firma Jung ist am günstigsten."; tr: "offer, supply<br><br>The offer from the Jung Company is the most attractive."; known: false }
    ListElement { txt: "Auftrag<br>(der Auftrag, die Aufträge)<br><br>Die Firma mit dem günstigsten Angebot bekommt den Auftrag."; tr: "order, contract<br><br>The firm with the best offer gets the order."; known: false }
    ListElement { txt: "ausrechnen<br>(ausrechnen, rechnete aus, hat ausgerechnet)<br><br>Können Sie mir ausrechnen, wieviel Quadratmeter Holz ich brauche?"; tr: "calculate, figure out<br><br>Can you calculate for me how many square meters of wood I need?"; known: false }
    ListElement { txt: "Betrieb<br>(der Betrieb, die Betriebe)<br><br>Unser Betrieb ist wirtschaftlich sehr gesund."; tr: "business, concern, operation, office<br><br>Our business is economically very sound."; known: false }
    ListElement { txt: "Buchführung<br>(die Buchführung, die Buchführungen)<br><br>Wir haben einige Fehler in der Buchführung entdeckt."; tr: "bookkeeping, accounting<br><br>We discovered a mistake in the bookkeeping."; known: false }
    ListElement { txt: "Fabrik<br>(die Fabrik, die Fabriken)<br><br>In unserer Fabrik wird die Produktion von Computern gesteuert."; tr: "factory<br><br>At our factory, production is guided by computers."; known: false }
    ListElement { txt: "Firma<br>(die Firma, die Firmen)<br><br>Die Firma Hertz &amp; Sohn gibt es schon seit über 100 Jahren."; tr: "firm<br><br>Hertz &amp; San have existed for over 100 years as a firm."; known: false }
    ListElement { txt: "Geschäft<br>(das Geschäft, die Geschäfte)<br><br>Wir müssen uns beeilen. Die Geschäfte schließen bald. Peter will mein altes Auto kaufen, aber ich mache nicht gerne Geschäfte mit Freunden."; tr: "business, store, deal, transaction<br><br>We have to hurry. The stores are closing soon. Peter wants to buy my old car, but I don't like to do business with friends."; known: false }
    ListElement { txt: "Industrie<br>(die Industrie, die Industrien)<br><br>Die Industrie klagt über die hohen Lohnkosten."; tr: "industry<br><br>Industry is complaining about high salary costs."; known: false }
    ListElement { txt: "Konkurrenz<br>(die Konkurrenz, kein Plural)<br><br>Trotz starker Konkurrenz hat unsere Firma den Auftrag bekommen."; tr: "competition<br><br>In spite of strong competition, our firm got the contract."; known: false }
    ListElement { txt: "Lager<br>(das Lager, die Lager)<br><br>Das eine Ersatzteil haben wir auf Lager, das andere bestellen wir."; tr: "stock, storage<br><br>We have one of the spare parts in stock; we'll order the other one."; known: false }
    ListElement { txt: "liefern<br>(liefern, lieferte, hat geliefert)<br><br>Wir liefern schnell und pünktlich."; tr: "deliver<br><br>We deliver quickly and on time."; known: false }
    ListElement { txt: "Produkt<br>(das Produkt, die Produkte)<br><br>Unsere Produkte sind zur Zeit konkurrenzlos."; tr: "product<br><br>Right now our products have no competition."; known: false }
    ListElement { txt: "Produktion<br>(die Produktion, kein Plural)<br><br>Wegen der vielen Aufträge musste die Produktion erhöht werden."; tr: "production<br><br>Production had to be increased because of the many contracts."; known: false }
    ListElement { txt: "Rechnung<br>(die Rechnung, die Rechnungen)<br><br>Diese Rechnung muss bis zum 3.11. bezahlt werden."; tr: "bill<br><br>This bill must be paid by November 3."; known: false }
    ListElement { txt: "senken<br>(senken, senkte, hat gesenkt)<br><br>Die Preise für die alten Modelle wurden gesenkt."; tr: "lower, cut<br><br>The prices for the old models were lowered."; known: false }
    ListElement { txt: "steigern<br>(steigern, steigerte, hat gesteigert)<br><br>Die Firma konnte ihren Umsatz um 10% steigern."; tr: "raise, increase<br><br>The firm was able to raise its sales by 10%."; known: false }
    ListElement { txt: "Steuer<br>(die Steuer, die Steuern)<br><br>Zu diesem Betrag kommt noch die Umsatzsteuer dazu."; tr: "tax<br><br>The sales tax must be added to this amount."; known: false }
    ListElement { txt: "U­matz<br>(der U­matz, die Umsätze)<br><br>Der Umsatz ist um 20% gestiegen."; tr: "sales, turnover<br><br>Sales have gone up 20%."; known: false }
    ListElement { txt: "Unternehmen<br>(das Unternehmen, die Unternehmen)<br><br>Die Unternehmen der Chemieindustrie haben gegen die neuen Wasserschutzgesetze protestiert."; tr: "enterprise, company<br><br>The chemical industry companies have protested the new water protection laws."; known: false }
    ListElement { txt: "Versicherung<br>(die Versicherung, die Versicherungen)<br><br>Eine Krankenversicherung ist in Deutschland für alle Studenten Pflicht."; tr: "insurance<br><br>Health insurance in Germany is required for all students."; known: false }
    ListElement { txt: "Werbung<br>(die Werbung, kein Plural)<br><br>Für das neue Produkt wird in Presse und Fernsehen Werbung gemacht."; tr: "advertising<br><br>There is advertising for the new product in the press and on TV."; known: false }
    ListElement { txt: "Wirtschaft<br>(die Wirtschaft, kein Plural)<br><br>Die Regierung hofft auf eine gute Wirtschaftsentwicklung."; tr: "economy, business<br><br>The government is hoping for good development in the economic sector."; known: false }
    ListElement { txt: "Abmachung<br>(die Abmachung, die Abmachungen)<br><br>Trotz unserer Abmachung will Ihre Firma die Waren nicht mehr umtauschen. Warum?"; tr: "agreement<br><br>In spite of our agreement, your firm won't exchange the goods. Why?"; known: false }
    ListElement { txt: "Bedarf<br>(der Bedarf, kein Plural)<br><br>Der Bedarf an Kleinwagen nimmt ab."; tr: "need<br><br>The need for small cars is going down."; known: false }
    ListElement { txt: "Bilanz<br>(die Bilanz, die Bilanzen)<br><br>Nach den Verlusten im letzten Jahr ist die Bilanz der Firma jetzt wieder positiv."; tr: "balance<br><br>After last year's lasses the balance of the firm is once again positive."; known: false }
    ListElement { txt: "Einnahme<br>(die Einnahme, die Einnahmen)<br><br>Die Einnahmen sind in den letzten Wochen gesunken."; tr: "income, revenue<br><br>Revenues have gone down in recent weeks."; known: false }
    ListElement { txt: "Ersatzteil<br>(das Ersatzteil, die Ersatzteile)<br><br>Die Werkstatt hat ein großes Ersatzteillager."; tr: "spare part<br><br>The garage has a large supply of spare parts."; known: false }
    ListElement { txt: "Export<br>(der Export, die Exporte)<br><br>Die Firma lebt vor allem von Exportaufträgen."; tr: "export, exportation<br><br>The firm lives mostly on its export orders."; known: false }
    ListElement { txt: "exportieren<br>(exportieren, exportierte, hat exportiert)<br><br>Diese Maschine wird nach Frankreich exportiert."; tr: "export<br><br>This machine will be exported to France."; known: false }
    ListElement { txt: "Garantie<br>(die Garantie, die Garantien)<br><br>Das Radio ist gebraucht. Eine Garantie kann ich Ihnen dafür nicht geben."; tr: "guarantee, warranty<br><br>The radio is second-hand. I can't give you a guarantee for it."; known: false }
    ListElement { txt: "geschäftlich<br>(geschäftlich)<br><br>Herr Benz ist geschäftlich verreist."; tr: "on/for business<br><br>Mr. Benz is away on business."; known: false }
    ListElement { txt: "Geschäftsführer<br>(der Geschäftsführer, die Geschäftsführerin f)<br><br>Ich möchte bitte den Geschäftsführer sprechen."; tr: "managing director, manager<br><br>I'd like to speak to the manager, please."; known: false }
    ListElement { txt: "Geschäftsleitung<br>(die Geschäftsleitung, die Geschäftsleitungen)<br><br>Die Büros der Geschäftsleitung sind im 3. Stock."; tr: "(the) management<br><br>The offices of the management are on the third floor."; known: false }
    ListElement { txt: "herstellen<br>(herstellen, stellte her, hat hergestellt)<br><br>Die Firma stellt seit über 60 Jahren Büromaschinen her."; tr: "manufacture, make<br><br>The company has been manufacturing office machines for over 60 years."; known: false }
    ListElement { txt: "Hersteller<br>(der Hersteller, die Hersteller)<br><br>Wir haben Computer verschiedener Hersteller im Programm."; tr: "manufacturer<br><br>We have computers from different manufacturers in our catalogue."; known: false }
    ListElement { txt: "Herstellung<br>(die Herstellung, kein Plural)<br><br>Die Gefahren bei der Herstellung chemischer Produkte wurden früher wenig beachtet."; tr: "manufacturing<br><br>The dangers involved in manufacturing chemical products were not previously recognized."; known: false }
    ListElement { txt: "Import<br>(der Import, die Importe)<br><br>Die Preise der Importwaren sind gesunken."; tr: "import<br><br>The prices of imported goods have fallen."; known: false }
    ListElement { txt: "importieren<br>(importieren, importierte, hat importiert)<br><br>Die Bundesrepublik hat dieses Jahr mehr Öl importiert als letztes Jahr."; tr: "import<br><br>The Federal Republic imported more oil this year than last year."; known: false }
    ListElement { txt: "Investition<br>(die Investition, die Investitionen)<br><br>Durch die hohen Investitionen für wirtschaftlichere Maschinen ist die Firma konkurrenzfähiger geworden."; tr: "investment<br><br>By increasing investment in more economical machines the company became more competitive."; known: false }
    ListElement { txt: "Krise<br>(die Krise, die Krisen)<br><br>Die wirtschaftliche Krise in der Textilindustrie hat viele Leute arbeitslos gemacht."; tr: "crisis<br><br>The economic crisis in the textile industry has caused unemployment for many people."; known: false }
    ListElement { txt: "Kundendienst<br>(der Kundendienst, die Kundendienste)<br><br>Unsere Waschmaschine war kaputt. Der Kundendienst kam sofort und hat die Maschine repariert."; tr: "customer service<br><br>Our washing machine was broken. The service (representative) came immediately and repaired the machine."; known: false }
    ListElement { txt: "Lieferung<br>(die Lieferung, die Lieferungen)<br><br>Die bestellten Ersatzteile kommen mit der nächsten Lieferung."; tr: "delivery<br><br>The ordered replacement parts we will arrive with the next deli­ very."; known: false }
    ListElement { txt: "Markt<br>(der Markt, die Märkte)<br><br>Auf dem Markt für Werkzeugmaschinen gibt es z. Z. einen harten Preiskampf."; tr: "market<br><br>At the moment prices are under heavy pressure in the machine tool market."; known: false }
    ListElement { txt: "Muster<br>(das Muster, die Muster)<br><br>Der Vertreter zeigte dem Händler Muster des Teppichprogramms seiner Firma."; tr: "sample<br><br>The representative showed the dealer samples of the different carpets made by his company."; known: false }
    ListElement { txt: "Nachfrage<br>(die Nachfrage, kein Plural)<br><br>Die Nachfrage nach Elektrokleingeräten ist stark gesunken."; tr: "inquiry, demand<br><br>The demand for electric appliances has dropped dramatically."; known: false }
    ListElement { txt: "ökonomisch<br>(ökonomisch)<br><br>Es wäre ökonomischer gewesen, die alten Maschinen nicht zu reparieren, sondern neue zu kaufen."; tr: "economical<br><br>It would have been more economical not to repair the old machines, but to buy new ones."; known: false }
    ListElement { txt: "produzieren<br>(produzieren, produzierte, hat produziert)<br><br>Ersatzteile für diese alten Geräte werden nicht mehr produziert."; tr: "produce<br><br>Replacement parts for these old appliances are no longer being produced."; known: false }
    ListElement { txt: "Profit<br>(der Profit, die Profite)<br><br>Bei dem letzten Geschäft haben wir keinen Profit gemacht."; tr: "profit<br><br>Our last transaction yielded no profit."; known: false }
    ListElement { txt: "Prospekt<br>(der Prospekt, die Prospekte)<br><br>Könnten Sie mir einen Prospekt für dieses Gerät geben."; tr: "prospectus, advertising brochure<br><br>Could you give me a prospectus for this device?"; known: false }
    ListElement { txt: "ruinieren<br>(ruinieren, ruinierte, hat ruiniert)<br><br>Die Firma wurde vor allem durch falsche Entscheidungen der Manager ruiniert."; tr: "ruin<br><br>The company was ruined primarily by poor decisions by the managers."; known: false }
    ListElement { txt: "selbständig<br>(selbständig)<br><br>Früher war er angestellt, jetzt ist er selbständig und hat ein eigenes Geschäft."; tr: "independent, self-employed<br><br>Previously he was employed, now he is self-employed and has his own business."; known: false }
    ListElement { txt: "Statistik<br>(die Statistik, die Statistiken)<br><br>Die Zahlen der Verkaufsstatistik sind wichtig für die Investitionsplanung."; tr: "statistics<br><br>The figures for the sales statistics are important for investment planning."; known: false }
    ListElement { txt: "Steigerung<br>(die Steigerung, die Steigerungen)<br><br>Ohne neue Mitarbeiter ist eine Steigerung der Produktion nicht möglich."; tr: "increase<br><br>Without new workers an increase in production is not possible."; known: false }
    ListElement { txt: "verbrauchen<br>(verbrauchen, verbrauchte, hat verbraucht)<br><br>Die neuen Maschinen verbrauchen weniger Strom als die alten."; tr: "consume, use up<br><br>The new machines consume less electricity than the old ones."; known: false }
    ListElement { txt: "Verbraucher<br>(der Verbraucher, die Verbraucher)<br><br>Die Verbraucher sind heute kritischer als früher."; tr: "consumer<br><br>Consumers are more critical than they used to be."; known: false }
    ListElement { txt: "versichern<br>(versichern, versicherte, hat versichert)<br><br>Das Haus ist gegen Feuer und Sturm versichert."; tr: "insure<br><br>The house is insured against fire and storm damage."; known: false }
    ListElement { txt: "Versorgung<br>(die Versorgung, kein Plural)<br><br>Bei einigen Herstellern gibt es Versorgungsprobleme mit Ersatzteilen."; tr: "supply<br><br>Several manufacturers have supply problems with replacement parts."; known: false }
    ListElement { txt: "wirtschaftlich<br>(wirtschaftlich)<br><br>Die wirtschaftliche Situation der Metallindustrie ist besser geworden."; tr: "economic<br><br>The economic situation in the metal industry has improved."; known: false }

}

