import QtQuick 2.2

ListModel {
    property string name: "06.4_Work"
    ListElement { txt: "Angelegenheit<br>(die Angelegenheit, die Angelegenheiten)<br><br>Um diese Angelegenheit kümmert sich Frau Rabe."; tr: "matter<br><br>Ms. Rabe is taking care of this matter."; known: false }
    ListElement { txt: "arbeitslos<br>(arbeitslos)<br><br>Sie war nur drei Monate arbeitslos."; tr: "out of work, unemployed<br><br>She was only out of work for three months."; known: false }
    ListElement { txt: "Aufgabe<br>(die Aufgabe, die Aufgaben)<br><br>Herr Weiss hat neue Aufgaben in einer anderen Abteilung übernommen."; tr: "job, task<br><br>Mr. Weis has taken a new job in another division."; known: false }
    ListElement { txt: "Bedingung<br>(die Bedingung, die Bedingungen)<br><br>Die Arbeitsbedingungen in unserer Firma sind gut. Ich habe die Bedingung gestellt, dass ich ein eigenes Büro bekomme."; tr: "condition<br><br>Work conditions are very good at our company. I made it a condition that I get an office of my own."; known: false }
    ListElement { txt: "beschäftigen<br>(beschäftigen, beschäftigte, hat beschäftigt)<br><br>Unsere Firma beschäftigt 130 Angestellte und Arbeiter."; tr: "occupy, employ<br><br>Our company employs 130 office employees and workers."; known: false }
    ListElement { txt: "bewerben<br>(bewerben, bewarb, hat beworben)<br><br>Ich habe mich bei zwei Firmen beworben."; tr: "apply for a job<br><br>I've applied to two companies for a job."; known: false }
    ListElement { txt: "Bewerbung<br>(die Bewerbung, die Bewerbungen)<br><br>Auf meine Bewerbung habe ich noch keine Antwort."; tr: "application<br><br>I still don't have any response to my application."; known: false }
    ListElement { txt: "Büro<br>(das Büro, die Büros)<br><br>Sonja arbeitet in einem Versicherungsbüro."; tr: "office<br><br>Sonja works in the office of an insurance company."; known: false }
    ListElement { txt: "Chef<br>(der Chef, die Chefs)<br><br>Mit unserem Chef kann man gut zusammenarbeiten."; tr: "boss<br><br>We can work well with our boss."; known: false }
    ListElement { txt: "Dienst<br>(der Dienst, die Dienste)<br><br>Nächste Woche habe ich Nachtdienst im Krankenhaus."; tr: "service, working hours, shift<br><br>Next week I have the night shift at the hospital."; known: false }
    ListElement { txt: "einstellen<br>(einstellen, stellte ein, hat eingestellt)<br><br>Wir schaffen die Arbeit nicht. Es müssen unbedingt ein paar neue Leute eingestellt werden."; tr: "employ, hire<br><br>We can't get the work done. We absolutely have to hire a few new people."; known: false }
    ListElement { txt: "Erfolg<br>(der Erfolg, die Erfolge)<br><br>Mit den neuen Produkten hat die Firma großen Erfolg."; tr: "success<br><br>The company is having great success with the new products."; known: false }
    ListElement { txt: "erfolgreich<br>(erfolgreich)<br><br>Sie ist eine erfolgreiche Geschäftsfrau."; tr: "successful<br><br>She is a successful business woman."; known: false }
    ListElement { txt: "erledigen<br>(erledigen, erledigte, hat erledigt)<br><br>Diese Sache muss unbedingt bis morgen erledigt werden."; tr: "take care of, settle<br><br>These things must absolutely be taken care of by tomorrow."; known: false }
    ListElement { txt: "Gehalt<br>(das Gehalt, die Gehälter)<br><br>Die Gehälter werden ab nächsten Monat um 2,7 % erhöht."; tr: "salary<br><br>Salaries will go up 2.7% next month."; known: false }
    ListElement { txt: "Karriere<br>(die Karriere, die Karrieren)<br><br>Von seinen Kollegen wird er bewundert, weil er sehr schnell Karriere gemacht hat."; tr: "career<br><br>He is admired by his colleagues for the rapid rise in his career."; known: false }
    ListElement { txt: "Kopie<br>(die Kopie, die Kopien)<br><br>Bitte machen Sie drei Kopien von dem Brief. Das Original behalte ich."; tr: "copy<br><br>Please make three copies of the letter. I'll keep the original."; known: false }
    ListElement { txt: "kündigen<br>(kündigen, kündigte, hat gekündigt)<br><br>Ich habe meine Stelle zum 1. Mai gekündigt."; tr: "resign, quit<br><br>I'm resigning as of May 1."; known: false }
    ListElement { txt: "Landwirtschaft<br>(die Landwirtschaft, kein Plural)<br><br>Früher hat er in der Landwirtschaft gearbeitet. Jetzt hat er eine Stelle in der Industrie."; tr: "farming, agriculture<br><br>He used to work in agriculture. Now he is in industry."; known: false }
    ListElement { txt: "Leistung<br>(die Leistung, die Leistungen)<br><br>Ihre berufliche Leistung wird von allen Kollegen anerkannt."; tr: "performance<br><br>Her professional performance is recognized by all her colleagues."; known: false }
    ListElement { txt: "Leitung<br>(die Leitung, kein Plural)<br><br>Die Geschäftsleitung hat die Arbeitszeiten geändert."; tr: "leadership, management<br><br>The company management has changed the working hours."; known: false }
    ListElement { txt: "Lohn<br>(der Lohn, die Löhne)<br><br>Wie hoch ist dein Stundenlohn?"; tr: "wage<br><br>How high is your hourly wage?"; known: false }
    ListElement { txt: "Personal<br>(das Personal, kein Plural)<br><br>Die Firma  Schmidt &amp; Koch' hat sehr gutes Personal."; tr: "personnel, staff<br><br>The 'Schmidt &amp; Koch' firm has a very good staff."; known: false }
    ListElement { txt: "Qualität<br>(die Qualität, die Qualitäten)<br><br>Mit der Qualität der neuen Möbel bin ich zufrieden."; tr: "quality<br><br>I'm satisfied with the quality of the new furniture."; known: false }
    ListElement { txt: "Stelle<br>(die Stelle, die Stellen)<br><br>In unserer Firma ist eine Stelle als Fahrer frei."; tr: "position, job, opening<br><br>Our company has an opening for a driver."; known: false }
    ListElement { txt: "Stellung<br>(die Stellung, die Stellungen)<br><br>Meine Frau hat eine gute Stellung als Verkäuferin in einem Kaufhaus."; tr: "job, position<br><br>My wife has a good job as a salesperson in a department store."; known: false }
    ListElement { txt: "tippen<br>(tippen, tippte, hat getippt)<br><br>Haben Sie den Brief an Herrn Behrens schon getippt?"; tr: "type<br><br>Have you already typed the letter to Mr. Behrens?"; known: false }
    ListElement { txt: "Urlaub<br>(der Urlaub, kein Plural)<br><br>Ich mache gerne im Winter Urlaub."; tr: "vacation, holiday's (BE)<br><br>I like to take a vacation in the winter."; known: false }
    ListElement { txt: "verantwortlich<br>(verantwortlich)<br><br>Herr Ahrens ist für die Qualitätskontrolle verantwortlich."; tr: "responsible<br><br>Mr. Ahrens is responsible for quality control."; known: false }
    ListElement { txt: "Vertrag<br>(der Vertrag, die Verträge)<br><br>Heute habe ich den Arbeitsvertrag mit meiner neuen Firma unterschrieben."; tr: "contract<br><br>Today I signed the contract with my new employer."; known: false }
    ListElement { txt: "vertreten<br>(vertreten, vertrat, hat vertreten)<br><br>Während des Urlaubs vertritt er die Abteilungsleiterin."; tr: "stand in for, represent, substitute for<br><br>He represents the head of the department during her vacation."; known: false }
    ListElement { txt: "Werk<br>(das Werk, die Werke)<br><br>Die Firma hat ein Werk in Unna und eins in Hagen."; tr: "factory<br><br>The company has a factory in Unna and another in Hagen."; known: false }
    ListElement { txt: "Werkstatt<br>(die Werkstatt, die Werkstätten)<br><br>Die Maschine muss in der Werkstatt repariert werden."; tr: "workshop, garage<br><br>The machine must be repaired in the workshop."; known: false }
    ListElement { txt: "Abteilung<br>(die Abteilung, die Abteilungen)<br><br>In unserer Abteilung ist das Betriebsklima sehr gut."; tr: "department, division<br><br>The work atmosphere is very good in our department."; known: false }
    ListElement { txt: "Aktie<br>(die Aktie, die Aktien)<br><br>Die Banken raten, jetzt Aktien zu kaufen."; tr: "stock<br><br>The banks advise us to buy stock now."; known: false }
    ListElement { txt: "Anforderung<br>(die Anforderung, die Anforderungen)<br><br>Die Anforderungen, die unsere Chefin stellt, sind hoch."; tr: "demand, requirement<br><br>The demands our boss is making are high."; known: false }
    ListElement { txt: "anstellen<br>(anstellen, stellte an, hat angestellt)<br><br>Sie ist nach der Probezeit fest angestellt worden."; tr: "employ<br><br>After a trial period she was permanently employed."; known: false }
    ListElement { txt: "Arbeitgeber<br>(der Arbeitgeber, die Arbeitgeber)<br><br>Die Gewerkschaft und die Arbeitgeber verhandeln seit zwei Wochen über einen neuen Tarifvertrag."; tr: "employer<br><br>The union and the employers have been working on a new contract for two weeks."; known: false }
    ListElement { txt: "Arbeitnehmer<br>(der Arbeitnehmer, die Arbeitnehmerin f)<br><br>Die Arbeitnehmer haben für den neuen Tarifvertrag gestimmt."; tr: "employee, worker<br><br>The workers voted for the new contract."; known: false }
    ListElement { txt: "Arbeitslosigkeit<br>(die Arbeitslosigkeit, kein Plural)<br><br>Die Arbeitslosigkeit ist im letzten Jahr um 2,7 % gestiegen."; tr: "unemployment<br><br>Unemployment has increased 2.7% in the past year."; known: false }
    ListElement { txt: "Arbeitsplatz<br>(der Arbeitsplatz, die Arbeitsplätze)<br><br>In der Schiffsindustrie gibt es immer weniger Arbeitsplätze."; tr: "job<br><br>There are fewer and fewer jobs in the shipbuilding industry."; known: false }
    ListElement { txt: "Arbeitszeit<br>(die Arbeitszeit, die Arbeitszeiten)<br><br>Die Arbeitszeit in unserem Betrieb ist von 7.30 Uhr bis 17.00 Uhr."; tr: "working hours<br><br>Working hours at our business are 7:30 am to 5:00 pm."; known: false }
    ListElement { txt: "Belastung<br>(die Belastung, die Belastungen)<br><br>Nachtdienst ist eine große Belastung für die Arbeiter."; tr: "strain<br><br>The night shift is a serious strain on the workers."; known: false }
    ListElement { txt: "Belegschaft<br>(die Belegschaft, die Belegschaften)<br><br>Die Belegschaft ist mit den neuen Urlaubsterminen einverstanden."; tr: "staff<br><br>The staff has agreed to the new vacation schedule."; known: false }
    ListElement { txt: "Beratung<br>(die Beratung, die Beratungen)<br><br>Bernd weiß noch nicht, welchen Beruf er lernen möchte. Er hat sich deshalb bei der Berufsberatung des Arbeitsamtes informiert."; tr: "advice<br><br>Bernd doesn't know yet what he wants to be. So he has gotten advice and information from the employment office."; known: false }
    ListElement { txt: "Diktat<br>(das Diktat, die Diktate)<br><br>Die Chefin spricht ihre Diktate auf Kassette."; tr: "dictation<br><br>The boss records her dictations on a cassette."; known: false }
    ListElement { txt: "Direktor<br>(der Direktor, die Direktoren)<br><br>Die Firma wird von zwei Direktoren geleitet."; tr: "director<br><br>The company is led by two directors."; known: false }
    ListElement { txt: "entlassen<br>(entlassen, entließ, hat entlassen)<br><br>Warum der Kollege Scholz entlassen wurde, weiß niemand."; tr: "let go, dismiss, fire<br><br>No one knows why our colleague Scholz was fired."; known: false }
    ListElement { txt: "Feierabend<br>(der Feierabend, die Feierabende)<br><br>Freitags haben wir schon um 13.00 Uhr Feierabend."; tr: "closing time<br><br>Fridays we close early, at 1 pm."; known: false }
    ListElement { txt: "Gewerkschaft<br>(die Gewerkschaft, die Gewerkschaften)<br><br>Die Gewerkschaften kämpfen seit Jahren für eine Arbeitszeitverkürzung."; tr: "(trade) union<br><br>The unions have been fighting for years for shorter hours."; known: false }
    ListElement { txt: "Handwerk<br>(das Handwerk, kein Plural)<br><br>Automechaniker ist seit Jahren der beliebteste Handwerksberuf bei Jungen."; tr: "manual work, trade, craft<br><br>Auto mechanics has far years been the favorite career choice for young men learning a trade,"; known: false }
    ListElement { txt: "Kollege<br>(der Kollege, die Kollegen)<br><br>In unserer Abteilung sagen alle Kollegen  du' zueinander.."; tr: "colleague<br><br>In our department all colleagues are on a first-name basis."; known: false }
    ListElement { txt: "Konferenz<br>(die Konferenz, die Konferenzen)<br><br>Auf der Vertreterkonferenz wurde der neue Verkaufsleiter vorgestellt."; tr: "conference, meeting<br><br>At the sales meeting the new sales director was introduced."; known: false }
    ListElement { txt: "Kongress<br>(der Kongress, die Kongresse)<br><br>Dr. Matz habe ich auf einem Medizinerkongress in Düsseldorf kennen gelernt."; tr: "conference, meeting, convention<br><br>I met Dr. Matz at a medical conference in Düsseldorf."; known: false }
    ListElement { txt: "Leiter<br>(der Leiter, die Leiter)<br><br>Vor sechs Jahren hat sie als Verkäuferin bei uns angefangen, jetzt ist sie schon Leiterin des Supermarktes."; tr: "manager, head,<br><br>She started out as a salesperson here six years ago; now she is already the manager of our supermarket."; known: false }
    ListElement { txt: "Mitarbeiter<br>(der Mitarbeiter, die Mitarbeiter)<br><br>Alle Mitarbeiter sind zu einer Betriebsversammlung eingeladen worden."; tr: "worker, employee<br><br>All employees were invited to a company meeting."; known: false }
    ListElement { txt: "Mitbestimmung<br>(die Mitbestimmung, kein Plural)<br><br>Die Mitbestimmung der Arbeitnehmer in den Betrieben ist keine wichtige politische Streitfrage mehr."; tr: "worker participation<br><br>The participation of employees in management decisions of the company is no longer an important of political issue."; known: false }
    ListElement { txt: "Misserfolg<br>(der Misserfolg, die Misserfolge)<br><br>Für die jüngsten wirtschaftlichen Misserfolge wird der Verkaufschef verantwortlich gemacht."; tr: "failure<br><br>The sales manager will be held responsible for the latest economic failure."; known: false }
    ListElement { txt: "Notizbuch<br>(das Notizbuch, die Notizbücher)<br><br>Mein Notizbuch ist mein  zweites Gedächtnis'."; tr: "date book, notebook<br><br>My notebook is my 'second memory."; known: false }
    ListElement { txt: "Praktikant<br>(der Praktikant, die Praktikanten)<br><br>In den Semesterferien arbeitet sie als Praktikantin in einer Textilfabrik."; tr: "trainee<br><br>During semester vacation she works as a trainee in a textile factory."; known: false }
    ListElement { txt: "Projekt<br>(das Projekt, die Projekte)<br><br>Unsere Gruppe arbeitet an einem geheimen Projekt."; tr: "project<br><br>Our group is working on a secret project."; known: false }
    ListElement { txt: "Schreibmaschine<br>(die Schreibmaschine, die Schreibmaschinen)<br><br>Wie schnell kannst du Schreibmaschine schreiben?"; tr: "typewriter<br><br>How fast can you type?"; known: false }
    ListElement { txt: "Sitzung<br>(die Sitzung, die Sitzungen)<br><br>Auf der letzten Sitzung der Geschäftsleitung wurde eine neue Arbeitszeitregelung besprochen."; tr: "meeting<br><br>At their last meeting the company executives discussed a new regulation of working hours."; known: false }
    ListElement { txt: "Streik<br>(der Streik, die Streiks)<br><br>Die Mehrheit der Beschäftigten stimmte für den Streik."; tr: "strike<br><br>The majority of employees voted for the strike."; known: false }
    ListElement { txt: "streiken<br>(streiken, streikte, hat gestreikt)<br><br>Die Kollegen streiken für kürzere Arbeitszeiten."; tr: "strike<br><br>The workers are striking for shorter hours."; known: false }
    ListElement { txt: "Tarif<br>(der Tarif, die Tarife)<br><br>Die Gewerkschaften verhandeln mit den Arbeitgebern über neue Gehaltstarife."; tr: "salary<br><br>The unions and employers are discussing new salaries."; known: false }
    ListElement { txt: "Termin<br>(der Termin, die Termine)<br><br>Montag ist der letzte Termin. Bis dahin muss die Ware beim Kunden sein,"; tr: "(delivery) date<br><br>Monday is the last date for deli very. The merchandise has to get to the client by then."; known: false }
    ListElement { txt: "Unterschrift<br>(die Unterschrift, die Unterschriften)<br><br>Der Vertrag ist ohne die Unterschrift von Frau Brand nicht gültig."; tr: "signature<br><br>The contract isn't valid without the signature of Ms. Brand."; known: false }
    ListElement { txt: "verpachten<br>(verpachten, verpachtete, hat verpachtet)<br><br>Er hat sein Geschäft verpachtet."; tr: "lease<br><br>He leased his business."; known: false }
    ListElement { txt: "Vertreter<br>(der Vertreter, die Vertreter)<br><br>Der Chef ist nicht da. Sie können aber mit seinem Vertreter sprechen."; tr: "representative<br><br>The boss isn't here, but you can speak with his representative."; known: false }
    ListElement { txt: "Vorgänger<br>(der Vorgänger, die Vorgänger)<br><br>Der neue Abteilungsleiter ist ein ganz anderer Mensch als sein Vorgänger."; tr: "predecessor<br><br>The new department head is very different from his predecessor."; known: false }
    ListElement { txt: "Zusammenarbeit<br>(die Zusammenarbeit, kein Plural)<br><br>Die Zusammenarbeit mit der neuen Kollegin klappt gut."; tr: "cooperation, collaboration,<br><br>Collaboration with the new colleague is going well."; known: false }
    ListElement { txt: "zusammenarbeiten<br>(zusammenarbeiten, arbeitete zusammen, hat zusammen gearbeitet)<br><br>Edith ist sehr nervös. Mit ihr kann man nicht gut zusammenarbeiten."; tr: "cooperate, collaborate, work with<br><br>Edith is very nervous. It's hard to collaborate with her."; known: false }
    ListElement { txt: "zuständig<br>(zuständig)<br><br>Wer ist in Ihrer Firma für Reklamationen zuständig?"; tr: "responsible<br><br>Who in your business is responsible for handling complaints?"; known: false }

}

