import QtQuick 2.2

ListModel {
    property string name: "08.1_Government_and_Politics"
    ListElement { txt: "Ausländer<br>(der Ausländer, die Ausländer)<br><br>Sie ist Ausländerin, aber sie spricht sehr gut Deutsch."; tr: "foreigner<br><br>She is a foreigner, but she speaks German very well."; known: false }
    ListElement { txt: "ausländisch<br>(ausländisch)<br><br>Ausländische Restaurants sind in der Bundesrepublik sehr beliebt."; tr: "foreign<br><br>Foreign restaurants are very popular in the Federal Republic."; known: false }
    ListElement { txt: "Bürger<br>(der Bürger, die Bürger)<br><br>Die Bürger sind von der Stadt eingeladen worden, die Straßenbaupläne zu diskutieren."; tr: "citizen<br><br>The city invited the citizens to discuss the plans for road construction,"; known: false }
    ListElement { txt: "Bürgermeister<br>(der Bürgermeister, die Bürgermeister)<br><br>Der Bürgermeister wurde schon dreimal wiedergewählt."; tr: "mayor<br><br>The mayor has already been reelected to three terms."; known: false }
    ListElement { txt: "Demokratie<br>(die Demokratie, die Demokratien)<br><br>Von 1918 bis 1933 gab es in Deutschland zum ersten Mal eine Demokratie."; tr: "democracy<br><br>From 1918 to 1933 there was a democracy for the first time in Germany."; known: false }
    ListElement { txt: "demokratisch<br>(demokratisch)<br><br>Es wird bezweifelt, dass die Wahlen demokratisch waren."; tr: "democratic<br><br>It's doubtful that the election was democratic."; known: false }
    ListElement { txt: "frei<br>(frei)<br><br>Die politischen Häftlinge sind immer noch nicht frei. In diesem Land kann ich frei meine Meinung sagen."; tr: "free, liberal<br><br>The political prisoners are still not free. In this country l can freely express my opinion."; known: false }
    ListElement { txt: "Freiheit<br>(die Freiheit, die Freiheiten)<br><br>Das Volk kämpft seit Jahren für seine Freiheit."; tr: "freedom<br><br>The people have been fighting for their freedom for years."; known: false }
    ListElement { txt: "Grenze<br>(die Grenze, die Grenzen)<br><br>Die Grenze zwischen den beiden Ländern wurde geschlossen."; tr: "border<br><br>The border between the two countries was closed."; known: false }
    ListElement { txt: "Heimat<br>(die Heimat, kein Plural)<br><br>Die Flüchtlinge dürfen nicht in ihre Heimat zurück."; tr: "home country<br><br>The refugees may not return to their home country."; known: false }
    ListElement { txt: "international<br>(international)<br><br>Auf der internationalen Währungskonferenz wurde die Dollarkrise diskutiert."; tr: "international<br><br>At the international currency conference the dollar crisis was discussed."; known: false }
    ListElement { txt: "Kanzler<br>(der Kanzler, die Kanzler)<br><br>Der Kanzler ist der Chef der Regierung."; tr: "chancellor<br><br>The chancellor is head of the government."; known: false }
    ListElement { txt: "Land<br>(das Land, die Länder)<br><br>Das Land braucht eine neue Regierung."; tr: "country<br><br>The country needs a new government."; known: false }
    ListElement { txt: "Macht<br>(die Macht, kein Plural)<br><br>Das Militär ist in dem Land seit Jahren an der Macht."; tr: "power<br><br>The military has been in power for years in that country."; known: false }
    ListElement { txt: "Macht<br>(die Macht, die Mächte)<br><br>Die beiden Großmächte USA und Russland verhandeln über eine Lösung des Konflikts."; tr: "power<br><br>Two major powers, the USA and Russia, are discussing a solution for the conflict."; known: false }
    ListElement { txt: "Minister<br>(der Minister, die Minister)<br><br>Die Ministerin wurde für den Misserfolg verantwortlich gemacht."; tr: "(cabinet) minister, cabinet secretary<br><br>The minister was held responsible for the failure."; known: false }
    ListElement { txt: "Öffentlichkeit<br>(die Öffentlichkeit, kein Plural)<br><br>In der Öffentlichkeit wird die Außenpolitik der Regierung gelobt."; tr: "public<br><br>The government's foreign policy is praised publicly."; known: false }
    ListElement { txt: "offiziell<br>(offiziell)<br><br>Eine offizielle Äußerung der Regierung zu diesem Problem gibt es bis jetzt nicht."; tr: "official<br><br>There's still no official government statement about this problem."; known: false }
    ListElement { txt: "Parlament<br>(das Parlament, die Parlamente)<br><br>Die Regierungsparteien haben im Parlament eine große Mehrheit."; tr: "parliament<br><br>The government parties have a large majority in parliament."; known: false }
    ListElement { txt: "Partei<br>(die Partei, die Parteien)<br><br>Das neue Programm wird in der Partei seit Monaten diskutiert."; tr: "party<br><br>The party has been discussing the new program for months."; known: false }
    ListElement { txt: "Politik<br>(die Politik, kein Plural)<br><br>In der Finanzpolitik der Regierung ist keine klare Linie zu erkennen."; tr: "policy<br><br>There's no clear line in the government's financial policy."; known: false }
    ListElement { txt: "politisch<br>(politisch)<br><br>Das ist eine wichtige politische Frage."; tr: "political<br><br>That is an important political question."; known: false }
    ListElement { txt: "Präsident<br>(der Präsident, die Präsidenten)<br><br>Nächstes Jahr wird ein neuer Präsident gewählt."; tr: "president<br><br>A new president will be elected next year."; known: false }
    ListElement { txt: "regieren<br>(regieren, regierte, hat regiert)<br><br>Das Land wird von fremden Mächten regiert."; tr: "rule<br><br>The country is ruled by foreign powers."; known: false }
    ListElement { txt: "Regierung<br>(die Regierung, die Regierungen)<br><br>Die Regierung ist seit zwei Jahren im Amt."; tr: "government<br><br>The government has been in power for two years."; known: false }
    ListElement { txt: "Republik<br>(die Republik, die Republiken)<br><br>1918 wurde Deutschland Republik."; tr: "republic<br><br>Germany became a republic in 1918."; known: false }
    ListElement { txt: "Staat<br>(der Staat, die Staaten)<br><br>Der Staat hat sehr viel Einfluss auf das Leben der Bürger."; tr: "country, nation, government, state<br><br>The government has much influence on the life of its citizens."; known: false }
    ListElement { txt: "staatlich<br>(staatlich)<br><br>Die Eisenbahn ist staatlich."; tr: "public<br><br>The railroad system is public."; known: false }
    ListElement { txt: "Tradition<br>(die Tradition, die Traditionen)<br><br>Es ist Tradition, dass der Parlamentspräsident Mitglied der stärksten Partei ist."; tr: "tradition<br><br>Tradition is that the president of the parliament belongs to the party in power."; known: false }
    ListElement { txt: "Verfassung<br>(die Verfassung, die Verfassungen)<br><br>Die Verfassung der Bundesrepublik ist noch sehr jung."; tr: "constitution<br><br>The constitution of Germany is still young."; known: false }
    ListElement { txt: "verhandeln<br>(verhandeln, verhandelte, hat verhandelt)<br><br>Die beiden Länder verhandeln über einen Friedensvertrag."; tr: "negotiate<br><br>The two countries are negotiating a peace treaty."; known: false }
    ListElement { txt: "Verhandlung<br>(die Verhandlung, die Verhandlungen)<br><br>Die Verhandlungen sind bis jetzt ohne Ergebnis geblieben."; tr: "negotiations<br><br>The negotiations still have had no results."; known: false }
    ListElement { txt: "Volk<br>(das Volk, die Völker)<br><br>Im Volk ist man mit der wirtschaftlichen Situation sehr unzufrieden."; tr: "people<br><br>The people are very dissatisfied with the economic situation."; known: false }
    ListElement { txt: "Wahl<br>(die Wahl, die Wahlen)<br><br>Es ist offen, wer die nächste Wahl gewinnt."; tr: "election<br><br>No one knows who will win the next election."; known: false }
    ListElement { txt: "wählen<br>(wählen, wählte, hat gewählt)<br><br>Im August wird ein neues Parlament gewählt."; tr: "elect<br><br>A new parliament will be elected in August."; known: false }
    ListElement { txt: "Abkommen<br>(das Abkommen, die Abkommen)<br><br>Die beiden Staaten verhandeln über ein neues Handelsabkommen."; tr: "agreement<br><br>The two countries are discussing a new trade agreement."; known: false }
    ListElement { txt: "Außenminister<br>(der Außenminister, die Außenminister)<br><br>Die Konferenz der Außenminister blieb ohne Ergebnis."; tr: "foreign minister, secretary of state (AE), foreign secretary (BE)<br><br>The secretaries of state conference had no results."; known: false }
    ListElement { txt: "Außenpolitik<br>(die Außenpolitik, kein Plural)<br><br>Im Parlament gab es Streit über die Außenpolitik."; tr: "foreign policy<br><br>In parliament there was disagreement about foreign policy."; known: false }
    ListElement { txt: "Botschaft<br>(die Botschaft, die Botschaften)<br><br>Die Visaabteilung der Botschaft ist nur morgens geöffnet."; tr: "embassy<br><br>The visa office of the embassy is only open in the morning."; known: false }
    ListElement { txt: "bürgerlich<br>(bürgerlich)<br><br>Das Bürgerliche Gesetzbuch trat im Jahr 1900 in Kraft."; tr: "civil<br><br>The civil code came into force in 1900."; known: false }
    ListElement { txt: "Demonstration<br>(die Demonstration, die Demonstrationen)<br><br>Im ganzen Land gab es Demonstrationen gegen die Schulreform."; tr: "demonstration<br><br>All over the country there were demonstrations against the school reform."; known: false }
    ListElement { txt: "Diplomat<br>(der Diplomat, die Diplomaten)<br><br>Der Diplomat wird verdächtigt, ein Spion zu sein."; tr: "diplomat<br><br>The diplomat is suspected of being a spy."; known: false }
    ListElement { txt: "diplomatisch<br>(diplomatisch)<br><br>Zwischen den beiden Ländern gibt es gute diplomatische Beziehungen."; tr: "diplomatic<br><br>There are good diplomatic relations between the two countries."; known: false }
    ListElement { txt: "einheimisch<br>(einheimisch)<br><br>Die Bevölkerung wird aufgefordert, nur einheimische Produkte zu kaufen."; tr: "local, native<br><br>People are advised to buy only local products."; known: false }
    ListElement { txt: "Fahne<br>(die Fahne, die Fahnen)<br><br>Die französische Trikolore war Vorbild für viele europäische Nationalfahnen."; tr: "flag<br><br>The French tricolor flag was the model for many European national flags."; known: false }
    ListElement { txt: "Finanzminister<br>(der Finanzminister, die Finanzminister)<br><br>Der Finanzminister fordert eine Erhöhung der Umsatzsteuer."; tr: "finance minister, secretary of the treasury<br><br>The finance minister is recommending a raise in sales taxes."; known: false }
    ListElement { txt: "gesetzlich<br>(gesetzlich)<br><br>Bei dem Bau der Fabrik sind gesetzliche Vorschriften verletzt worden."; tr: "legal<br><br>Legal regulations were violated when the factory was built."; known: false }
    ListElement { txt: "Gleichberechtigung<br>(die Gleichberechtigung, kein Plural)<br><br>Die Gewerkschaft fordert die volle Gleichberechtigung von Mann und Frau."; tr: "equality, equal rights<br><br>The union is recommending complete equality between men and women."; known: false }
    ListElement { txt: "Grundgesetz<br>(das Grundgesetz, kein Plural)<br><br>Das Grundgesetz ist die Verfassung der Bundesrepublik."; tr: "basic law<br><br>The Basic Law is the constitution of the Federal Republic of Germany."; known: false }
    ListElement { txt: "herrschen<br>(herrschen, herrschte, hat geherrscht)<br><br>In dem Land herrscht seit Jahren eine Militärregierung."; tr: "rule<br><br>For years the military has ruled in that country."; known: false }
    ListElement { txt: "Ideologie<br>(die Ideologie, die Ideologien)<br><br>Es ist schwer, mit Leuten zu diskutieren, die fest an ihre Ideologie glauben."; tr: "ideology<br><br>It is hard to have a discussion with people who strongly believe in their ideology."; known: false }
    ListElement { txt: "inländisch<br>(inländisch)<br><br>Die inländische Industrie klagt über die niedrigen Preise der ausländischen Konkurrenz."; tr: "national, domestic, home<br><br>National industries complain about the low prices of foreign competition."; known: false }
    ListElement { txt: "Innenminister<br>(der Innenminister, die Innenminister)<br><br>Der Innenminister verteidigte die Maßnahmen der Polizei."; tr: "minister of the interior, home secretary [GB], secretary of state (AE)<br><br>The minister of the interior defended the police actions."; known: false }
    ListElement { txt: "Innenpolitik<br>(die Innenpolitik, kein Plural)<br><br>In der Innenpolitik gibt es einen heftigen Streit um die Krankenversicherung."; tr: "domestic policy<br><br>In domestic policy there is a big debate about health insurance."; known: false }
    ListElement { txt: "Kabinett<br>(das Kabinett, die Kabinette)<br><br>Das Kabinett beschließt heute die Vorschläge des Innenministers."; tr: "cabinet<br><br>Today the cabinet will vote on the secretary of the interior's plans."; known: false }
    ListElement { txt: "Kaiser<br>(der Kaiser, die Kaiser)<br><br>Bis 1918 hatte Deutschland einen Kaiser."; tr: "emperor n, empress<br><br>Germany had an emperor until 1918."; known: false }
    ListElement { txt: "Kapitalismus<br>(der Kapitalismus, kein Plural)<br><br>Für den Politiker sind Kapitalismus und soziale Gerechtigkeit keine Gegensätze."; tr: "capitalism<br><br>For the politician, capitalism and civil rights are not opposites."; known: false }
    ListElement { txt: "kapitalistisch<br>(kapitalistisch)<br><br>Es wird kritisiert, dass im kapitalistischen Wirtschaftssystem der Unterschied zwischen Armen und Reichen zu groß sei."; tr: "capitalist<br><br>Capitalist economies are criticized because the difference between rich and poor is supposedly too great."; known: false }
    ListElement { txt: "Koalition<br>(die Koalition, die Koalitionen)<br><br>Die Koalition hat sich auf ein Regierungsprogramm geeinigt."; tr: "coalition<br><br>The coalition has agreed on a government program."; known: false }
    ListElement { txt: "Kommunismus<br>(der Kommunismus, kein Plural)<br><br>Der Streit zwischen Kapitalismus und Kommunismus war früher härter als heute."; tr: "communism<br><br>There used to be more difference of opinion between capitalism and communism than there is today.­"; known: false }
    ListElement { txt: "Kommunistisch<br>(Kommunistisch)<br><br>Der Handel zwischen den kommunistischen und den kapitalistischen Ländern ist stärker geworden."; tr: "communist<br><br>Trade between communist and capitalist countries has grown."; known: false }
    ListElement { txt: "konservativ<br>(konservativ)<br><br>Die konservativen Parteien sind gegen die Schulreform."; tr: "conservative<br><br>The conservative parties are against school reform."; known: false }
    ListElement { txt: "Kundgebung<br>(die Kundgebung, die Kundgebungen)<br><br>Die Kundgebung der Gewerkschaft war nur schwach besucht."; tr: "rally, assembly<br><br>Not many came to the union rally."; known: false }
    ListElement { txt: "König<br>(der König, die Könige)<br><br>Der schwedische König hat keine große politische Macht."; tr: "king n, queen<br><br>The Swedish king hasn't much political power."; known: false }
    ListElement { txt: "Königreich<br>(das Königreich, die Königreiche)<br><br>Es gibt nur noch wenige Königreiche, die meisten Länder sind Republiken."; tr: "kingdom<br><br>There are very few kingdoms today; most countries are republics."; known: false }
    ListElement { txt: "liberal<br>(liberal)<br><br>Die liberale und die konservative Partei haben eine Koalition vereinbart."; tr: "liberal, middle-of-the-road<br><br>The liberal and conservative parties have joined in a coalition."; known: false }
    ListElement { txt: "Mehrheit<br>(die Mehrheit, die Mehrheiten)<br><br>Für ein solches Gesetz gibt es im Parlament keine Mehrheit."; tr: "majority<br><br>There's no majority in parliament for such a law."; known: false }
    ListElement { txt: "Ministerpräsident<br>(der Ministerpräsident, die Ministerpräsidentin f)<br><br>Die Ministerpräsidentin ist im Volk beliebt."; tr: "prime minister<br><br>The prime minister is very popular with the people."; known: false }
    ListElement { txt: "Nachfolger<br>(der Nachfolger, die Nachfolger)<br><br>Der Nachfolger des gestorbenen Innenministers ist noch nicht bekannt."; tr: "successor<br><br>The successor to the late Minister of the Interior is still unknown."; known: false }
    ListElement { txt: "Nation<br>(die Nation, die Nationen)<br><br>Die ganze Nation wünscht ein Ende des langen Krieges."; tr: "nation<br><br>The whole nation would like an end to the long war."; known: false }
    ListElement { txt: "national<br>(national)<br><br>Die nationalen Gesetze in Westeuropa sollen einheitlicher werden."; tr: "national<br><br>National laws in western Europe are supposed to become more unified."; known: false }
    ListElement { txt: "Opposition<br>(die Opposition, kein Plural)<br><br>Die Oppositionsparteien kritisierten die Regierung."; tr: "opposition<br><br>The opposition parties criticized the government."; known: false }
    ListElement { txt: "Propaganda<br>(die Propaganda, kein Plural)<br><br>Die Regierung bezeichnet die Kritik der Opposition als Propaganda."; tr: "propaganda<br><br>The government calls the opposition's criticism propaganda."; known: false }
    ListElement { txt: "Provinz<br>(die Provinz, die Provinzen)<br><br>Während des Wahlkampfes besuchte der Präsident alle Provinzen."; tr: "province<br><br>During the campaign the president visited every province."; known: false }
    ListElement { txt: "Provinz<br>(die Provinz, kein Plural)<br><br>In der Provinz gibt es nur wenige Theater."; tr: "the provinces n (area outside the main cities)<br><br>There are not many theaters in the provinces."; known: false }
    ListElement { txt: "Rede<br>(die Rede, die Reden)<br><br>Die Rede des Politikers bekam viel Beifall."; tr: "speech, talk<br><br>The politician's speech got a lot of applause."; known: false }
    ListElement { txt: "Redner<br>(der Redner, die Redner)<br><br>Die Redner auf der Kundgebung mussten von der Polizei geschützt werden."; tr: "speaker<br><br>The speaker at the rally had to have police protection."; known: false }
    ListElement { txt: "Reform<br>(die Reform, die Reformen)<br><br>Seit Monaten gibt es heftigen Streit um die Reform der Steuergesetze."; tr: "reform<br><br>For months there has been conflict over the reform in the tax laws."; known: false }
    ListElement { txt: "Regierungschef<br>(der Regierungschef, die Regierungschefs)<br><br>Die Regierungschefin ist auf einer Auslandsreise."; tr: "head of the government<br><br>The head of the government has gone on a foreign trip."; known: false }
    ListElement { txt: "Revolution<br>(die Revolution, die Revolutionen)<br><br>Wenn die soziale Lage nicht besser wird, besteht die Gefahr einer Revolution."; tr: "revolution<br><br>If the social condition doesn't get better, there's a danger of revolution,"; known: false }
    ListElement { txt: "Rücktritt<br>(der Rücktritt, die Rücktritte)<br><br>Der Regierungschef nahm den Rücktritt des Finanzministers an."; tr: "resignation<br><br>The head of the government accepted the resignation of the finance minister."; known: false }
    ListElement { txt: "sozial<br>(sozial)<br><br>Die alten Steuergesetze sind unsozial."; tr: "social<br><br>The old tax laws are anti-social."; known: false }
    ListElement { txt: "Sozialismus<br>(der Sozialismus, kein Plural)<br><br>Der Sozialismus kam am Ende der 8Oer Jahre in eine große Krise."; tr: "socialism<br><br>At the end of the eighties socialism entered a time of great crisis."; known: false }
    ListElement { txt: "sozialistisch<br>(sozialistisch)<br><br>Die sozialistische Partei wählte einen neuen Parteivorsitzenden."; tr: "socialist<br><br>The Socialist Party elected a new party chair."; known: false }
    ListElement { txt: "Spion<br>(der Spion, die Spione)<br><br>Der Spion wurde verhaftet."; tr: "spy<br><br>The spy was arrested."; known: false }
    ListElement { txt: "Stellvertreter<br>(der Stellvertreter, die Stellvertreter)<br><br>Der Stellvertreter des Bürgermeisters leitet die Sitzung."; tr: "deputy, representative<br><br>The deputy of the mayor took charge of the meeting."; known: false }
    ListElement { txt: "stimmen<br>(stimmen, stimmte, hat gestimmt)<br><br>52,5 % der Wähler stimmten für die Regierungsparteien."; tr: "vote<br><br>52.5% voted for the government parties."; known: false }
    ListElement { txt: "unabhängig<br>(unabhängig)<br><br>Das Land muss von Importen unabhängiger werden."; tr: "independent<br><br>The country must become more independent of imports."; known: false }
    ListElement { txt: "Unabhängigkeit<br>(die Unabhängigkeit, kein Plural)<br><br>Unabhängigkeit von den Großmächten ist das wichtigste Ziel der Regierungspolitik."; tr: "independence<br><br>Independence from the great powers is the most important goal of the government policy."; known: false }
    ListElement { txt: "Unruhe<br>(die Unruhe, die Unruhen)<br><br>Bei dieser Unruhe kann man nicht arbeiten. In den westlichen Provinzen des Landes gibt es politische Unruhen."; tr: "disturbance<br><br>You can't work with this disturbance! In the western provinces of the country there are political disturbances."; known: false }
    ListElement { txt: "Unterdrückung<br>(die Unterdrückung, kein Plural)<br><br>Nur durch harte Unterdrückung der Opposition kann die Regierung an der Macht bleiben."; tr: "suppression<br><br>The government can stay in power only with strong suppression of the opposition."; known: false }
    ListElement { txt: "Wahlkampf<br>(der Wahlkampf, die Wahlkämpfe)<br><br>Es ist noch nicht klar, wer im Wahlkampf die besseren Argumente hat."; tr: "election campaign<br><br>It's not clear yet who has the better arguments in the election campaign."; known: false }

}

